edit-chroot: Fix spinner to check for command's exit status.

diff --git a/host-bin/edit-chroot b/host-bin/edit-chroot
--- a/host-bin/edit-chroot
+++ b/host-bin/edit-chroot
@@ -163,25 +163,32 @@ getmountpoint() {
 
 # Prints out a fancy spinner that updates every time a line is fed in, unless
 # the output is not to a tty, in which case it just prints a new line.
-# $1: number of lines between each update of the spinner (default: 1)
+# $1: number of lines between each update of the spinner
+# $2...: Command to be run
 # Erases the line each time, so it will always be at position 0.
 # Either expect this and put text later in the line, or give this its own line.
 spinner() {
+    local spin="$1"
+    shift
     if [ -t 2 ]; then
-        mawk -Winteractive '
+        # Keep track of the exit status of the piped command
+        ret="`(("$@" || echo "$?" 1>&3) | mawk -Winteractive '
             BEGIN {
                 printf "\r"
             }
             {
-                y = (y+1) % '"${1:-1}"'
+                y = (y+1) % '"$spin"'
                 if (y == 0) {
                     x = (x+1) % 4
                     printf substr("\|/-", x+1, 1) "\r"
                 }
-            }' 1>&2
+            }' 1>&2) 3>&1`"
+        if [ -n "$ret" ]; then
+            return "$ret"
+        fi
     else
         echo 1>&2
-        cat > /dev/null
+        "$@" 1>/dev/null
     fi
 }
 
@@ -224,7 +231,7 @@ for NAME in "$@"; do
         fi
         # Delete the chroot
         echo -n "  Deleting $CHROOT..." 1>&2
-        rm -rvf --one-file-system "$CHROOT" | spinner 1000
+        spinner 1000 rm -rvf --one-file-system "$CHROOT"
         echo "Finished deleting $CHROOT" 1>&2
         continue
     fi
@@ -241,9 +248,9 @@ for NAME in "$@"; do
             fi
         fi
         echo -n "  Backing up $CHROOT to $dest..." 1>&2
-        tar --checkpoint=100 --checkpoint-action=exec=echo --one-file-system \
-            -V "crouton:backup.${date%-*}${date#*-}-$NAME" \
-            -caf "$dest" -C "$CHROOTS" "$NAME" | spinner
+        spinner 1 tar --checkpoint=100 --checkpoint-action=exec=echo \
+            --one-file-system -V "crouton:backup.${date%-*}${date#*-}-$NAME" \
+            -caf "$dest" -C "$CHROOTS" "$NAME"
         echo "Finished backing up $CHROOT to $dest" 1>&2
     fi
 
@@ -281,8 +288,8 @@ for NAME in "$@"; do
         fi
         echo -n "  Restoring $src to $CHROOT..." 1>&2
         mkdir -p "$CHROOT"
-        tar --checkpoint=200 --checkpoint-action=exec=echo --one-file-system \
-            -xaf "$src" -C "$CHROOT" --strip-components=1 | spinner
+        spinner 1 tar --checkpoint=200 --checkpoint-action=exec=echo \
+            --one-file-system -xaf "$src" -C "$CHROOT" --strip-components=1
         echo "Finished restoring $src to $CHROOT" 1>&2
     fi
 
@@ -389,10 +396,10 @@ for NAME in "$@"; do
                 error 1 "Unable to create directory for $target"
             fi
             echo -n "  Copying to $target..." 1>&2
-            cp -av --one-file-system "$CHROOT" "$target" | spinner 200
+            spinner 200 cp -av --one-file-system "$CHROOT" "$target"
             echo "Finished copying to $target" 1>&2
             echo -n "  Deleting old $CHROOT..." 1>&2
-            rm -rfv --one-file-system "$CHROOT" | spinner 1000
+            spinner 1000 rm -rfv --one-file-system "$CHROOT"
             echo "Finished deleting old $CHROOT" 1>&2
         else
             if ! mkdir -p "`dirname "$target"`"; then
