Add edit-chroot filesystem type checks. Fixes #803
Don't backup to tmpfs, advise not to move keys to tmpfs, don't move chroot to
non-ext.

diff --git a/host-bin/edit-chroot b/host-bin/edit-chroot
--- a/host-bin/edit-chroot
+++ b/host-bin/edit-chroot
@@ -65,6 +65,16 @@ Options:
 # Common functions
 . "$BINDIR/../installer/functions"
 
+# Returns the mountpoint a path is on. The path doesn't need to exist.
+# $1: the path to check
+# outputs on stdout
+getmountpoint() {
+    mp="`readlink -m "$1"`"
+    while ! stat -c '%m' "$mp" 2>/dev/null; do
+        mp="${mp%/*}"
+    done
+}
+
 # Process arguments
 while getopts 'abc:def:k:lm:ry' f; do
     case "$f" in
@@ -134,6 +144,12 @@ if [ -n "$ALLCHROOTS" ]; then
     fi
 fi
 
+# If TARBALL is unspecified and we're in /, put the tarball in ~/Downloads
+if [ -n "$BACKUP$RESTORE" -a -z "$TARBALL" -a "$PWD" = '/' \
+        -a -d '/home/chronos/user/Downloads' ]; then
+    TARBALL="/home/chronos/user/Downloads/"
+fi
+
 # If multiple chroots are listed, KEYFILE and MOVE must be empty or directories.
 if [ $# -gt 1 -a -f "$KEYFILE" -a ! "$KEYFILE" = '-' ]; then
     error 2 "Multiple chroots specified, but $KEYFILE is not a directory."
@@ -143,9 +159,33 @@ elif [ $# -gt 1 -a -f "$TARBALL" ]; then
     error 2 "Multiple chroots specified, but $TARBALL is not a directory."
 fi
 
+# Don't allow moving to non-ext filesystems
+if [ -n "$MOVE" ] && \
+        df -T "`getmountpoint "$MOVE"`" | awk '$2~"^ext"{exit 1}'; then
+    error 2 "Chroots can only be moved to ext filesystems."
+fi
+
+# Don't allow backing up to tmpfs filesystems
+if [ -n "$BACKUP" ] && ! df -T "`getmountpoint "${TARBALL:-.}"`" \
+                            | awk '$2=="tmpfs"{exit 1}'; then
+    error 2 "Chroots cannot be backed up to temporary filesystems."
+fi
+
 # We need to run as root
 if [ ! "$USER" = root -a ! "$UID" = 0 ]; then
     error 2 "$APPLICATION must be run as root."
+fi
+
+# Strongly advise against moving a keyfile to a tmpfs path
+if [ "${KEYFILE:--}" != '-' ] && \
+        ! df -T "`getmountpoint "$KEYFILE"`" | awk '$2=="tmpfs"{exit 1}'; then
+    echo -n '\
+Moving a keyfile to a temporary filesystem is a really good way to permanently
+lose access to your chroot. If you still want to do this, wait for 15 seconds.
+Otherwise: HIT CTRL-C RIGHT NOW > ' 1>&2
+    sleep 15
+    echo \
+'...okay. Be sure to put the keyfile somewhere safe before you reboot.' 1>&2
 fi
 
 # If we're restoring and specified a tarball and no name, detect the name.
@@ -203,27 +243,11 @@ if [ -n "$TARBALL" ] && \
     mkdir -p "$TARBALL"
 fi
 
-# If TARBALL is unspecified and we're in /, put the tarball in ~/Downloads
-if [ -n "$BACKUP$RESTORE" -a -z "$TARBALL" -a "$PWD" = '/' \
-        -a -d '/home/chronos/user/Downloads' ]; then
-    TARBALL="/home/chronos/user/Downloads/"
-fi
-
 # Avoid kernel panics due to slow I/O
 disablehungtask
 
 # Make sure we always exit with echo on the tty.
 addtrap "stty echo 2>/dev/null"
-
-# Returns the mountpoint a path is on. The path doesn't need to exist.
-# $1: the path to check
-# outputs on stdout
-getmountpoint() {
-    mp="`readlink -m "$1"`"
-    while ! stat -c '%m' "$mp" 2>/dev/null; do
-        mp="${mp%/*}"
-    done
-}
 
 # Prints out a fancy spinner that updates every time a line is fed in, unless
 # the output is not to a tty, in which case it just prints a new line.
