enter-chroot: Clean up dbus user detection.

diff --git a/host-bin/enter-chroot b/host-bin/enter-chroot
--- a/host-bin/enter-chroot
+++ b/host-bin/enter-chroot
@@ -335,11 +335,14 @@ if [ -n "$NOLOGIN" ]; then
 else
     # Launch the system dbus
     if [ -x "$CHROOT/bin/dbus-daemon" ]; then
+        # Try to detect the dbus user by parsing its configuration file
+        # If it fails, or if the user does not exist, `id -un '$dbususer'`
+        # will fail, and we fallback on a default user name ("messagebus")
         dbususer=`echo "cat /busconfig/user/text()" \
-            | xmllint --shell "$CHROOT/etc/dbus-1/system.conf" \
-            | grep '^[a-z][-a-z0-9_]*$' 2>/dev/null || true`
+            | xmllint --shell "$CHROOT/etc/dbus-1/system.conf" 2>/dev/null \
+            | grep '^[a-z][-a-z0-9_]*$' || true`
         env -i chroot "$CHROOT" su -c "
-            dbususer=\"$dbususer\""'
+            dbususer='$dbususer'"'
             pidfile="/var/run/dbus/pid"
             if [ -f "$pidfile" ]; then
                 if grep -q "^dbus-daemon" "/proc/`cat "$pidfile"`/cmdline" \
@@ -349,8 +352,8 @@ else
                 rm -f "$pidfile"
             fi
             mkdir -p /var/run/dbus
-            dbususer=`id -un "$dbususer" 2>/dev/null || echo "messagebus"`
-            dbusgrp=`id -gn "$dbususer" 2>/dev/null || echo "messagebus"`
+            dbususer="`id -un \"$dbususer\" 2>/dev/null || echo \"messagebus\"`"
+            dbusgrp="`id -gn \"$dbususer\" 2>/dev/null || echo \"messagebus\"`"
             chown "$dbususer:$dbusgrp" /var/run/dbus
             dbus-daemon --system --fork' - root
     fi
