Check that the link /etc/localtime points to is a valid timezone in the guest OS.

diff --git a/host-bin/enter-chroot b/host-bin/enter-chroot
--- a/host-bin/enter-chroot
+++ b/host-bin/enter-chroot
@@ -202,6 +202,23 @@ fi
 # Soft-link resolv.conf so that updates are automatically propagated
 ln -sf '/var/host/shill/resolv.conf' "$CHROOT/etc/resolv.conf"
 
+# Sanity check of the timezone setting
+if [ "`readlink $CHROOT/etc/localtime`" = "/var/host/timezone/localtime" ]; then
+    LOCALTIME=`readlink /var/lib/timezone/localtime || true`
+
+    if [ -z "$LOCALTIME" ]; then
+        echo "WARNING: the timezone configuration in Chromium OS seems invalid \
+(/var/lib/timezone/localtime is not a symbolic link)." 1>&2
+        echo "To set the chroot's timezone, run the following (for Ubuntu/Debian):
+sudo dpkg-reconfigure tzdata" 1>&2
+    elif [ ! -e "$CHROOT$LOCALTIME" ]; then
+        echo "WARNING: the timezone selected in Chromium OS does not exist \
+inside the chroot ($LOCALTIME)." 1>&2
+        echo "To set the chroot's timezone, run the following (for Ubuntu/Debian): 
+sudo dpkg-reconfigure tzdata" 1>&2
+    fi
+fi
+
 # Follows and fixes dangerous symlinks, returning the canonicalized path.
 fixabslinks() {
     local p="$CHROOT/$1" c
