enter-chroot: Run cras-audio-update.
I wanted to integrate it better with rc.local, but rc.local runs
with all FDs closed (for good reasons), while we want user
interactivity.

diff --git a/host-bin/enter-chroot b/host-bin/enter-chroot
--- a/host-bin/enter-chroot
+++ b/host-bin/enter-chroot
@@ -684,12 +684,22 @@ if [ -n "$NOLOGIN" ]; then
         fi
     fi
 else
-    # Run rc.local
-    if [ -n "$firstrun" -a -x "$CHROOT/etc/rc.local" ]; then
-        chrootcmd 'exec /etc/rc.local >/dev/null 2>/dev/null </dev/null' \
-            || ret=$?
+    if [ -n "$firstrun" ]; then
+        # Run rc.local
+        if [ -x "$CHROOT/etc/rc.local" ]; then
+            chrootcmd 'exec /etc/rc.local >/dev/null 2>/dev/null </dev/null' \
+                || ret=$?
+            if [ ! "$ret" = 0 ]; then
+                echo "WARNING: /etc/rc.local failed with code $ret" 1>&2
+                ret=0
+            fi
+        fi
+
+        # Run cras-audio-update
+        chrootcmd 'hash cras-audio-update 2>/dev/null && \
+                       cras-audio-update -a -q' || ret=$?
         if [ ! "$ret" = 0 ]; then
-            echo "WARNING: /etc/rc.local failed with code $ret" 1>&2
+            sleep 5
             ret=0
         fi
     fi
