Use wrapped, randomly-generated passphrases for encryption.
Breaks the old method of encryption; use an old version of crouton if you need
to migrate your data.

This is far more secure, and you can store your keys separately from the chroot
if you so desire, for maximum security (within the capabilities of this system).

diff --git a/host-bin/mount-chroot b/host-bin/mount-chroot
--- a/host-bin/mount-chroot
+++ b/host-bin/mount-chroot
@@ -7,6 +7,7 @@ APPLICATION="${0##*/}"
 CHROOTS="`readlink -f "\`dirname "$0"\`/../chroots"`"
 CREATE=''
 ENCRYPT=''
+KEYFILE=''
 PRINT=''
 
 USAGE="$APPLICATION [options] name [...]
@@ -16,6 +17,9 @@ Mounts one or more encrypted chroots into a root-only directory.
 Options:
     -c CHROOTS  Directory the chroots are in. Default: $CHROOTS
     -e          If the chroot is not encrypted, encrypt it.
+    -k KEYFILE  File or directory to store the (encrypted) encryption keys in.
+                If unspecified, the keys will be stored in the chroot if doing a
+                first encryption, or auto-detected on existing chroots.
     -n          Create the chroot if it doesn't exist.
     -p          Prints out the path to the mounted directory on stdout."
 
@@ -28,10 +32,11 @@ error() {
 }
 
 # Process arguments
-while getopts 'c:enp' f; do
+while getopts 'c:ek:np' f; do
     case "$f" in
     c) CHROOTS="$OPTARG";;
     e) ENCRYPT='y';;
+    k) KEYFILE="$OPTARG";;
     n) CREATE='y';;
     p) PRINT='y';;
     \?) error 2 "$USAGE";;
@@ -62,41 +67,31 @@ for NAME in "$@"; do
     # Check for existence
     CHROOT="$CHROOTS/$NAME"
     movesrc=''
-    if [ ! -d "$CHROOT" ]; then
-        for CHROOTSRC in "$CHROOT:ecryptfs="*; do
-            if [ -d "$CHROOTSRC" ]; then
-                break
-            fi
-        done
-    elif [ "${CHROOT%:ecryptfs=*}" = "$CHROOT" ]; then
-        if [ -z "$ENCRYPT" ]; then
+    if [ -d "$CHROOT" ]; then
+        if [ ! -f "$CHROOT/.ecryptfs" -a -z "$ENCRYPT" ]; then
             if [ -n "$PRINT" ]; then
                 echo "$CHROOT"
             fi
             continue
         fi
-        movesrc="$CHROOT"
-        # If we were in the middle of a move, continue it
-        for CHROOTSRC in "$CHROOT:ecryptfs="*; do
-            if [ -d "$CHROOTSRC" ]; then
+        # Check for non-encrypted files, which means we may need to move them.
+        for file in "$CHROOT/"*; do
+            if [ "${file#*/ECRYPTFS_FNEK_ENCRYPTED}" = "$file" ]; then
+                movesrc="$CHROOT"
                 break
             fi
         done
-        CHROOTSRC="${CHROOTSRC%"*"}"
-    fi
-    if [ ! -d "$CHROOTSRC" -a ! -d "$CHROOT" ]; then
-        if [ -z "$CREATE" ]; then
-            error 1 "$CHROOT not found."
-        elif [ -z "$ENCRYPT" ]; then
-            mkdir -p "$CHROOT"
-            if [ -n "$PRINT" ]; then
-                echo "$CHROOT"
-            fi
-            continue
+    elif [ -z "$CREATE" ]; then
+        error 1 "$CHROOT not found."
+    elif [ -z "$ENCRYPT" ]; then
+        mkdir -p "$CHROOT"
+        if [ -n "$PRINT" ]; then
+            echo "$CHROOT"
         fi
-        CHROOTSRC="$CHROOTS/$NAME:ecryptfs="
+        continue
     fi
 
+    CHROOTSRC="$CHROOT"
     CHROOT="$CHROOTS/.secure/$NAME"
     mkdir -p "$CHROOTSRC"
     if [ -n "$PRINT" ]; then
@@ -116,17 +111,36 @@ for NAME in "$@"; do
             chromeos-setdevpasswd
         fi
 
+        # Detect the key file
+        if [ -z "$KEYFILE" ]; then
+            KEYFILE="$CHROOTSRC/.ecryptfs"
+            if [ -f "$KEYFILE" ]; then
+                header="`head -n1 "$KEYFILE"`"
+                if [ -n "$header" ]; then
+                    KEYFILE="$header"
+                fi
+            fi
+        elif [ "${KEYFILE#/}" = "$KEYFILE" ]; then
+            KEYFILE="$PWD/$KEYFILE"
+        fi
+        if [ -d "$KEYFILE" -o ! "${KEYFILE%/}" = "$KEYFILE" ]; then
+            KEYFILE="${KEYFILE%/}/$NAME"
+        fi
+        if ! mkdir -p "`dirname "$KEYFILE"`"; then
+            error 1 "Unable to create directory for $KEYFILE"
+        fi
+
         # Create a root-only mount directory and mount in there
         mkdir -m 700 -p "$CHROOT"
         chown root:root "$CHROOTS/.secure"
         chmod 700 "$CHROOTS/.secure"
 
-        # Grab the signature and construct the mount arguments
-        sig="${CHROOTSRC##*:ecryptfs=}"
-
-        # If we just created it, choose and append the sig to the file name.
+        # If we just created it, choose and create the keyfile.
         passphrase=''
-        if [ -z "$sig" ]; then
+        if [ ! -f "$CHROOTSRC/.ecryptfs" ]; then
+            if [ -e "$KEYFILE" ]; then
+                error 1 "Encryption key file $KEYFILE already exists. Refusing to overwrite!"
+            fi
             echo -n "Choose an encryption passphrase for $NAME: " 1>&2
             stty -echo
             while [ -z "$passphrase" ]; do
@@ -146,85 +160,137 @@ for NAME in "$@"; do
                 fi
                 confirmation=''
             done
-            echo 1>&2
             stty echo
-            sig="`echo -n "$passphrase" | ecryptfs-add-passphrase - | sed 's/.*\[\(.*\)\].*/\1/'`"
-            if [ -z "$sig" ]; then
-                error 1 'Failed to get ecryptfs passphrase signature.'
-            fi
-            oldsrc="$CHROOTSRC"
-            CHROOTSRC="$CHROOTSRC$sig"
-            if [ "$oldsrc" = "$CHROOTSRC" ] \
-                    || ! mv -f "$oldsrc" "$CHROOTSRC"; then
-                error 1 "Failed to record encryption signature for $NAME."
-            fi
-        fi
-
-        mnt="ecryptfs_sig=$sig,ecryptfs_fnek_sig=$sig"
-        mnt="$mnt,no_sig_cache,ecryptfs_cipher=aes,ecryptfs_key_bytes=16"
-        mnt="$mnt,ecryptfs_enable_filename_crypto=y,ecryptfs_passthrough=n"
-        # Key must be last so that we can append options to it.
-        mnt="$mnt,key=passphrase"
-
-        # On ecryptfs versions prior to 94, the passphrase_passwd_fd option did
-        # not properly handle pipes, so we can't safely pass the passphrase
-        # automatically when the chroot was just created. Instead, reset
-        # passphrase and let ecryptfs ask for it again.
-        if [ -n "$passphrase" ] \
-                && ecryptfsd -V | (read _ _ v; [ "$v" -lt 94 ]); then
-            echo 'Encrypted directory created; continuing with mount...' 1>&2
-            passphrase=''
-        fi
-
-        # ecryptfs tries to write to something in / on success, but it can't, so
-        # it will always fail. Check ourselves whether it was successful or not.
-        # Eat the error message and only display it if we failed.
-        stty -echo
-        if [ -n "$passphrase" ]; then
-            # We already have the passphrase, so pass it in via an FD
-            mnt="$mnt:passphrase_passwd_fd=0"
-            err="`echo "passphrase_passwd=$passphrase" \
-                  | mount -t ecryptfs -o "$mnt" "$CHROOTSRC" "$CHROOT" 2>&1 \
-                    || true`"
-            passphrase=''
-        else
-            echo -n "Encryption passphrase for $NAME: " 1>&2
-            err="`mount -t ecryptfs -o "$mnt" "$CHROOTSRC" "$CHROOT" 2>&1 \
-                    || true`"
             echo 1>&2
+
+            echo -n 'Generating keys (move the mouse to generate entropy)...' 1>&2
+            key="`hexdump -v -n32 -e'"%02x"' /dev/random`"
+            fnek="`hexdump -v -n32 -e'"%02x"' /dev/random`"
+            echo 'done' 1>&2
+
+            # Create key file
+            wrappedkey="`mktemp`"
+            wrappedfnek="`mktemp`"
+            TRAP="rm -f \"$wrappedkey\" \"$wrappedfnek\";$TRAP"
+            trap "$TRAP" INT HUP 0
+            echo -n "$key
+$passphrase" | ecryptfs-wrap-passphrase "$wrappedkey" -
+            echo -n "$fnek
+$passphrase" | ecryptfs-wrap-passphrase "$wrappedfnek" -
+            unset key fnek
+            echo | cat - "$wrappedkey" "$wrappedfnek" > "$KEYFILE"
+            if [ ! -f "$CHROOTSRC/.ecryptfs" ]; then
+                echo "$KEYFILE" > "$CHROOTSRC/.ecryptfs"
+            fi
+        elif [ ! -f "$KEYFILE" ]; then
+            error 1 "Unable to find encryption key file $KEYFILE"
+        else
+            echo -n "Enter encryption passphrase for $NAME: " 1>&2
+            stty -echo
+            read passphrase
+            stty echo
+            echo 1>&2
+
+            wrappedkey="`mktemp`"
+            wrappedfnek="`mktemp`"
+            TRAP="rm -f \"$wrappedkey\" \"$wrappedfnek\";$TRAP"
+            trap "$TRAP" INT HUP 0
+
+            # Extract wrapped keys from keyfile
+            tail -c 160 "$KEYFILE" | head -c 80 > "$wrappedkey"
+            tail -c 80 "$KEYFILE" > "$wrappedfnek"
         fi
-        stty echo
-        if ! mountpoint -q "$CHROOT"; then
-            error 1 "Failed to mount $NAME:${err#Passphrase:}"
+
+        # Add keys to keychain and extract 
+        keysig="`echo -n "$passphrase" \
+            | ecryptfs-unwrap-passphrase "$wrappedkey" - \
+            | ecryptfs-add-passphrase - \
+            | sed 's/.*\[\(.*\)\].*/\1/'`"
+        fneksig="`echo -n "$passphrase" \
+            | ecryptfs-unwrap-passphrase "$wrappedfnek" - \
+            | ecryptfs-add-passphrase - \
+            | sed 's/.*\[\(.*\)\].*/\1/'`"
+        if [ -z "$keysig" -o -z "$fneksig" ]; then
+            error 1 "Failed to decrypt $NAME."
+        fi
+
+        mnt="ecryptfs_sig=$keysig,ecryptfs_fnek_sig=$fneksig"
+        mnt="$mnt,no_sig_cache,ecryptfs_cipher=aes,ecryptfs_key_bytes=16"
+        mnt="$mnt,ecryptfs_passthrough=n,ecryptfs_unlink_sigs"
+
+        if ! mount -i -t ecryptfs -o "$mnt" "$CHROOTSRC" "$CHROOT"; then
+            error 1 "Failed to mount $NAME."
         fi
     fi
 
     # Perform the move
-    if [ -n "$movesrc" ]; then
-        echo -n "Encrypting $NAME; please wait..." 1>&2
-        failedmove=''
-        for dir in "$movesrc/"* "$movesrc/".*; do
-            if [ -z "${dir#"$movesrc/."}" -o -z "${dir#"$movesrc/.."}" ] \
-                    || [ ! -e "$dir" ]; then
-                continue
-            fi
-            if ! mv -f "$dir" "$CHROOT/"; then
-                failedmove=1
-                break
-            fi
-            echo -n . 1>&2
-        done
-        if [ -z "$failedmove" ] && ! rmdir "$movesrc"; then
-            echo 1>&2
-            echo -n "Unable to remove old $NAME directory." 1>&2
-            failedmove=1
-        fi
-        if [ -n "$failedmove" ]; then
-            echo 1>&2
-            error 1 "Encrypting $NAME failed. Please try again." 1>&2
-        fi
-        echo 'done!' 1>&2
+    if [ -z "$movesrc" ]; then
+        continue
     fi
+    response=y
+    for file in "$movesrc/"*; do
+        if [ ! "${file#*/ECRYPTFS_FNEK_ENCRYPTED}" = "$file" ]; then
+            echo -n \
+"About to continue encrypting the unencrypted portion of $NAME.
+If this is unexpected, then it could mean that someone's trying to inject files
+into your encrypted chroot, potentially allowing them to steal your data.
+Please choose one of the following options:
+yes  -- You are sure you want to continue moving the files in. They're yours.
+del  -- You do not like these files and want them deleted permanently.
+list -- You do not know what these files are and want to list them.
+no   -- You don't want to decide one way or another quite yet.
+> " 1>&2
+            read response
+            break
+        fi
+    done
+    case "$response" in
+    y*|Y*) (
+        echo -n "Encrypting $NAME; please wait..." 1>&2
+        cd "$movesrc"
+        tmp="`mktemp -d --tmpdir=. 'ECRYPTFS_MOVE_STAGING_XXXXXX'`"
+        find -not -name 'ECRYPTFS_FNEK_ENCRYPTED*' \
+             -not -wholename './ECRYPTFS_MOVE_STAGING_*' \
+             -not -wholename '.' \
+             -not -wholename './.ecryptfs' \
+             -exec mkdir -p "$tmp/{}" ';' \
+             -exec rmdir "$tmp/{}" ';' \
+             '(' -prune , -exec mv -f '{}' "$tmp/{}" ';' ')' 1>&2
+        for tmp in ECRYPTFS_MOVE_STAGING_*; do
+            (
+                cd "$tmp"
+                find '!' '(' -type d -exec test -d "$CHROOT/{}" ';' ')' \
+                     '(' -prune , -exec mv -f '{}' "$CHROOT/{}" ';' ')' \
+                     -exec echo -n . ';' 1>&2
+                find -depth -type d -not -wholename . \
+                     -exec test -d "$CHROOT/{}" ';' \
+                     -exec rmdir '{}' ';' 1>&2
+            )
+            rmdir "$tmp" 2>/dev/null || true
+        done
+        echo 'done.' 1>&2
+    );;
+    d*|D*) (
+        echo "Deleting unencrypted files in $NAME; please wait..." 1>&2
+        cd "$movesrc"
+        find -not -name 'ECRYPTFS_FNEK_ENCRYPTED*' \
+             -not -wholename '.' \
+             -not -wholename './.ecryptfs' \
+             '(' -prune , -exec rm -rvf '{}' ';' ')' 1>&2
+        echo 'Done.' 1>&2
+    );;
+    l*|L*) (
+        echo "Listing unencrypted files in $NAME; please wait..." 1>&2
+        cd "$movesrc"
+        find -not -name 'ECRYPTFS_FNEK_ENCRYPTED*' \
+             -not -name 'ECRYPTFS_MOVE_STAGING_*' \
+             -not -wholename '.' \
+             -not -wholename './.ecryptfs' \
+             -print -prune 1>&2
+        echo 'Done.' 1>&2
+        exit 2
+    );;
+    esac
 done
 
 exit 0
