Remove environment variable $container
Instead of inspecting the environment variable $container, check whether we are
able to do some operations and act responsively.

diff --git a/host-bin/unmount-chroot b/host-bin/unmount-chroot
--- a/host-bin/unmount-chroot
+++ b/host-bin/unmount-chroot
@@ -238,11 +238,7 @@ unmount() {
     # point actually ends with ' (deleted)')
     # umount has a bug and may return 0 when many mount points cannot be
     # unmounted, so we call it once per mount point ('-n 1')
-    if [ -n "$container" ]; then
-        arg='-l'
-    else
-        arg=''
-    fi
+    arg=''
     while ! sed "s=\\\\040=//=g" /proc/mounts | cut -d' ' -f2 | filter \
               | sed -e 's=//= =g;s/^\(\(.*\) (deleted)\)$/\1\n\2/' \
               | sort -r | xargs --no-run-if-empty -d '
@@ -272,6 +268,11 @@ unmount() {
             if [ -z "$printonly" ]; then
                 echo "Sending SIG$SIGNAL to processes under $CHROOTSRC..." 1>&2
             fi
+            # If there is no process running under $CHROOTSRC and we cannot
+            # unmount, then use lazy unmount.
+            # FIXME: This is a hack for running in containers, since we cannot
+            # unmount recursive bindmount in it.
+            arg='-l'
             for root in /proc/*/root; do
                 if [ ! -r "$root" ] \
                         || [ ! "`readlink -f "$root"`" = "$base" ]; then
@@ -285,6 +286,7 @@ unmount() {
                 if [ -z "$printonly" ]; then
                     kill "-$SIGNAL" "$pid" 2>/dev/null || true
                 fi
+                arg=''
             done
 
             # Escalate
@@ -326,10 +328,12 @@ done
 
 # Re-disable USB persistence (the Chromium OS default) if we no longer
 # have chroots running with a root in removable media
-if [ -z "$container" ] && checkusage "$ROOT/media"; then
+if checkusage "$ROOT/media"; then
     for usbp in /sys/bus/usb/devices/*/power/persist; do
         if [ -e "$usbp" ]; then
-            echo 0 > "$usbp"
+            # Don't fail since we don't have permission to write /sys/* if we are in
+            # container.
+            echo 0 > "$usbp" || true
         fi
     done
 fi
diff --git a/installer/ubuntu/bootstrap b/installer/ubuntu/bootstrap
--- a/installer/ubuntu/bootstrap
+++ b/installer/ubuntu/bootstrap
@@ -31,7 +31,7 @@ Check your internet connection or proxy settings and try again.'
     fi
 fi
 
-# Patch debootstrap so that it retries downloading packages
+# Patch debootstrap so that it retries downloading packages and not mounting /sys
 echo 'Patching debootstrap...' 1>&2
 if awk '
     t == 3 && /warning RETRY/ { print "sleep 1"; t=4 }
@@ -42,7 +42,7 @@ if awk '
         sub(/continue 2; fi/, "failed=y")
         t=1
     }
-    /if \[ -d \"\$TARGET\/sys\" \] && \\/ { sub(/if/, "if [ -z \"$container\" ] \&\&") }
+    /if \[ -d \"\$TARGET\/sys\" \] && \\/ { sub(/if/, "if false \&\&") }
     1
     END { if (t != 4) exit 1 }
         ' "$tmp/functions" > "$tmp/functions.new"; then
@@ -67,8 +67,8 @@ if [ ! -f "$tmp/scripts/$RELEASE" ]; then
     ln -s "$tmp/scripts/$BOOTSTRAP_RELEASE" "$tmp/scripts/$RELEASE"
 fi
 
-# We are not able to mknod in containers, so make a fake mknod for debootstrap.
-if [ -n "$container" ]; then
+# Create a fake mknod for debootstrap if we don't have CAP_MKNOD.
+if ! capmknod; then
     mkdir "$tmp/bin"
     echo "touch \$1" > "$tmp/bin/mknod"
     chmod +x "$tmp/bin/mknod"
diff --git a/installer/ubuntu/prepare b/installer/ubuntu/prepare
--- a/installer/ubuntu/prepare
+++ b/installer/ubuntu/prepare
@@ -219,38 +219,30 @@ export DEBIAN_FRONTEND=noninteractive
 
 # Run debootstrap second stage if it hasn't already happened
 if [ -r /debootstrap ]; then
-    # Debootstrap doesn't like anything mounted under /sys or /var when it runs
+    # Debootstrap doesn't like anything mounted under /var when it runs.
     # We request a re-mount after bootstrapping, so these mounts will be fixed.
     # We also can't detect the mounts properly due to the chroot, so we have to
-    # recursively find mountpoints under /sys, and hardcode /var umounts.
-    # However, if we are in container, debootstrap cannot mount /sys, so don't
-    # unmount it.
-    if [ -z "$container" ]; then
-        find /sys/* -maxdepth 2 -depth -type d \
-            -exec mountpoint -q {} \; -exec umount {} \;
-    else
+    # hardcode /var umounts.
+    if mountpoint -q '/var/run/crouton-ext'; then
         umount '/var/run/crouton-ext'
     fi
     umount '/var/run/lock' '/var/run'
-    # Create a fake mknod if we are in container.
-    if [ -n "$container" ]; then
+    # Create a fake mknod for debootstrap if we don't have CAP_MKNOD.
+    if ! capmknod; then
         cp /bin/mknod /bin/mknod.old
         echo "touch \$1" > /bin/mknod
     fi
     # Start the bootstrap
     /debootstrap/debootstrap --second-stage
-    if [ -n "$container" ]; then
-        # Mark makedev as installed.
+    # If we cannot mknod, the installation of makedev will fail, so mark it as
+    # installed manually.
+    if ! capmknod; then
         awk '
           BEGIN { matched = 0 }
           /^Package: makedev$/ { matched = 1 }
           matched == 1 && /^Status:/ { sub($4, "installed"); matched = 0 }
           1' /var/lib/dpkg/status > /var/lib/dpkg/status.new
         mv -f /var/lib/dpkg/status.new /var/lib/dpkg/status
-
-        # Deny all services to start in container.
-        echo exit 101 > /usr/sbin/policy-rc.d
-        chmod +x /usr/sbin/policy-rc.d
     fi
     # Clean contents of /var/run (since we'll always be mounting over it).
     rm -rf --one-file-system /var/run/*
