Override powerd_suspend persist if running a chroot from removable media.
powerd_suspend usually disables USB device persist on suspend, since Chromium OS
is designed to handle it and it saves a half a second during suspend and resume.
If you're using a chroot on an SD card or USB stick, however this will cause the
chroot to break when you suspend, which is generally considered a bad thing.

This modifies powerd_suspend on the fly to not disable persist on USB devices.
It establishes an overlay on /usr/bin, since it is normally read-only. The
overlay is removed in a best-effort manner when there are no more external-media
chroots mounted.

diff --git a/host-bin/unmount-chroot b/host-bin/unmount-chroot
--- a/host-bin/unmount-chroot
+++ b/host-bin/unmount-chroot
@@ -85,27 +85,36 @@ checkusage() {
     if [ -n "$FORCE" ]; then
         return 0
     fi
-    local pid ppid proot root
+    local b="${1%/}/" pid ppid proot prootdir root rootdir
     for root in /proc/*/root; do
-        if [ -r "$root" ] && [ "`readlink -f "$root"`" = "$base" ]; then
-            pid="${root#/proc/}"
-            pid="${pid%/root}"
-            ppid="`ps -p "$pid" -o ppid= 2>/dev/null`"
-            if [ -z "$ppid" ] || [ "$ppid" -eq 1 ]; then
-                continue
-            fi
-            proot="/proc/$ppid/root"
-            if [ -r "$proot" ] && [ "`readlink -f "$proot"`" = "$base" ]; then
-                continue
-            fi
-            if grep -q 'CROUTON=CORE' "/proc/$pid/environ"; then
-                continue
-            fi
-            if [ -n "$PRINT" ]; then
-                ps -p "$pid" -o pid= -o cmd= || true
-            fi
-            return 1
+        if [ ! -r "$root" ]; then
+            continue
         fi
+        rootdir="`readlink -f "$root"`"
+        rootdir="${rootdir%/}/"
+        if [ "${rootdir#"$b"}" = "$rootdir" ]; then
+            continue
+        fi
+        pid="${root#/proc/}"
+        pid="${pid%/root}"
+        ppid="`ps -p "$pid" -o ppid= 2>/dev/null`"
+        if [ -z "$ppid" ] || [ "$ppid" -eq 1 ]; then
+            continue
+        fi
+        proot="/proc/$ppid/root"
+        if [ -r "$proot" ]; then
+            prootdir="`readlink -f "$proot"`"
+            if [ "${prootdir%/}/" = "$rootdir" ]; then
+                continue
+            fi
+        fi
+        if grep -q 'CROUTON=CORE' "/proc/$pid/environ"; then
+            continue
+        fi
+        if [ -n "$PRINT" ]; then
+            ps -p "$pid" -o pid= -o cmd= || true
+        fi
+        return 1
     done
     return 0
 }
@@ -227,5 +236,18 @@ for NAME in "$@"; do
     # More sync for more safety
     sync
 done
+
+# Remove /usr/bin override if it's no longer necessary (nothing important is
+# running with a root in removable media)
+if mountpoint -q /usr/bin && checkusage /media; then
+    newbin="`readlink '/usr/bin/env'`"
+    newbin="${newbin%/env}"
+    # Split the umount calls so if the first fails, the second won't happen.
+    if umount '/usr/bin' 2>/dev/null; then
+        # These may fail if you opened a new crosh. It doesn't hurt to leave it.
+        umount "$newbin" 2>/dev/null || true
+        rmdir "$newbin" 2>/dev/null || true
+    fi
+fi
 
 exit $ret
