Fix error messages when running unmount-chroot -a on an empty directory.

diff --git a/host-bin/unmount-chroot b/host-bin/unmount-chroot
--- a/host-bin/unmount-chroot
+++ b/host-bin/unmount-chroot
@@ -128,6 +128,9 @@ checkusage() {
 
 # If we specified all chroots, bring in all chroots.
 if [ -n "$ALLCHROOTS" ]; then
+    if [ ! -d "$CHROOTS" ]; then
+        error 1 "$CHROOTS not found."
+    fi
     set -- "$CHROOTS/"*
 fi
 
@@ -150,8 +153,10 @@ unmount() {
     # Check for existence
     CHROOT="$CHROOTS/$NAME"
     if [ ! -d "$CHROOT" ]; then
-        echo "$CHROOT not found." 1>&2
-        ret=1
+        if [ -z "$ALLCHROOTS" ]; then
+            echo "$CHROOT not found." 1>&2
+            ret=1
+        fi
         return 0
     fi
 
