merged from upstream#master

diff --git a/chroot-bin/croutonpowerd b/chroot-bin/croutonpowerd
--- a/chroot-bin/croutonpowerd
+++ b/chroot-bin/croutonpowerd
@@ -14,11 +14,15 @@ Options:
     -i --inhibit           Inhibits powerd for the duration of the command, or
                            forever if no command is specified.
     -p --poke -deactivate  Pings powerd to prevent activation.
+    --suspend              Switches to Chromium OS and triggers a suspend.
     --daemon               Enters daemon mode where idleness and screensaver
                            inhibition are passed on to Chromium OS's powerd."
 
 INHIBITSLEEP='30'
 DAEMONSLEEP='15'
+
+# Common functions
+. "`dirname "$0"`/../installer/functions"
 
 # Check if we need to pass through to another command
 EXEC="${0##*/}"
@@ -31,10 +35,8 @@ esac
 case "$1" in
 -i|--inhibit) CMD='i';;
 -p|--poke|-deactivate) CMD='p';;
---daemon) CMD='d'
-    if [ -n "$EXEC" ]; then
-        exec "$EXEC" "$@"
-    fi;;
+--suspend) CMD='s';;
+--daemon) CMD='d';;
 *)  if [ -z "$EXEC" ]; then
         echo "$USAGE" 1>&2
         exit 2
@@ -42,8 +44,13 @@ case "$1" in
     exec "$EXEC" "$@";;
 esac
 
+hostdbus=''
+if hash host-dbus 2>/dev/null; then
+    hostdbus='host-dbus'
+fi
+
 pingpowerd() {
-    host-dbus dbus-send --system --dest=org.chromium.PowerManager \
+    $hostdbus dbus-send --system --dest=org.chromium.PowerManager \
                         --type=method_call /org/chromium/PowerManager \
                         org.chromium.PowerManager.HandleUserActivity || true
 }
@@ -58,7 +65,7 @@ elif [ "$CMD" = 'i' ]; then
         sleep "$INHIBITSLEEP"
     done &
     pid=$!
-    trap "kill $pid 2>/dev/null || true" INT HUP 0
+    addtrap "kill '$pid' 2>/dev/null"
     if [ -n "$EXEC" ]; then
         "$EXEC" "$@"
     elif [ -n "$2" ]; then
@@ -67,7 +74,20 @@ elif [ "$CMD" = 'i' ]; then
     else
         wait $pid
     fi
-else
+elif [ -n "$EXEC" ]; then
+    exec "$EXEC" "$@"
+elif [ "$CMD" = 's' ]; then
+    if hash croutoncycle 2>/dev/null; then
+        croutoncycle cros
+    fi
+    $hostdbus dbus-send --system --dest=org.chromium.PowerManager \
+                        --type=method_call /org/chromium/PowerManager \
+                        org.chromium.PowerManager.RequestSuspend || true
+elif [ "$CMD" = 'd' ]; then
+    if [ -z "$DISPLAY" ]; then
+        error 1 'Cannot launch daemon: $DISPLAY not specified.'
+    fi
+
     # Daemon
     xdgs='/usr/bin/xdg-screensaver'
     xi2pid=''
diff --git a/host-bin/edit-chroot b/host-bin/edit-chroot
--- a/host-bin/edit-chroot
+++ b/host-bin/edit-chroot
@@ -3,10 +3,12 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+set -e
+
 APPLICATION="${0##*/}"
 BACKUP=''
-BINDIR="`dirname "$0"`"
-CHROOTS="`readlink -f "\`dirname "$0"\`/../chroots"`"
+BINDIR="`dirname "\`readlink -f "$0"\`"`"
+CHROOTS="`readlink -f "$BINDIR/../chroots"`"
 DELETE=''
 ENCRYPT=''
 KEYFILE=''
@@ -114,7 +116,16 @@ fi
 # If we're restoring and specified a tarball and no name, detect the name.
 if [ -n "$RESTORE" -a -n "$TARBALL" -a $# = 0 ]; then
     echo 'Detecting chroot name...' 1>&2
-    NAME="`tar -tf "$TARBALL" 2>/dev/null | head -n 1`"
+    label="`tar --test-label -f "$TARBALL" 2>/dev/null`"
+    if [ -n "$label" ]; then
+        if [ "${label#crouton:backup}" = "$label" ]; then
+            error 2 "$TARBALL doesn't appear to be a valid crouton backup."
+        fi
+        NAME="${label#*-}"
+    else
+        # Old backups just use the first folder name
+        NAME="`tar -tf "$TARBALL" 2>/dev/null | head -n 1`"
+    fi
     if [ -z "$NAME" ]; then
         error 2 "$TARBALL doesn't appear to be a valid tarball."
     fi
@@ -134,8 +145,11 @@ if [ -n "$BACKUP$RESTORE" -a -z "$TARBALL" -a "$PWD" = '/' \
     TARBALL="/home/chronos/user/Downloads/"
 fi
 
+# Avoid kernel panics due to slow I/O
+disablehungtask
+
 # Make sure we always exit with echo on the tty.
-addtrap "stty echo 2>/dev/null || true"
+addtrap "stty echo 2>/dev/null"
 
 # Returns the mountpoint a path is on. The path doesn't need to exist.
 # $1: the path to check
@@ -147,22 +161,35 @@ getmountpoint() {
     done
 }
 
-# Prints out a fancy spinner that updates every time a line is fed in.
-# $1: number of lines between each update of the spinner (default: 1)
+# Prints out a fancy spinner that updates every time a line is fed in, unless
+# the output is not to a tty, in which case it just prints a new line.
+# $1: number of lines between each update of the spinner
+# $2...: Command to be run
 # Erases the line each time, so it will always be at position 0.
 # Either expect this and put text later in the line, or give this its own line.
 spinner() {
-    mawk -Winteractive '
-        BEGIN {
-            printf "\r"
-        }
-        {
-            y = (y+1) % '"${1:-1}"'
-            if (y == 0) {
-                x = (x+1) % 4
-                printf substr("\|/-", x+1, 1) "\r"
+    local spin="$1"
+    shift
+    if [ -t 2 ]; then
+        # Keep track of the exit status of the piped command
+        ret="`(("$@" || echo "$?" 1>&3) | mawk -Winteractive '
+            BEGIN {
+                printf "\r"
             }
-        }' 1>&2
+            {
+                y = (y+1) % '"$spin"'
+                if (y == 0) {
+                    x = (x+1) % 4
+                    printf substr("\|/-", x+1, 1) "\r"
+                }
+            }' 1>&2) 3>&1`"
+        if [ -n "$ret" ]; then
+            return "$ret"
+        fi
+    else
+        echo 1>&2
+        "$@" 1>/dev/null
+    fi
 }
 
 # Process each chroot
@@ -192,14 +219,19 @@ for NAME in "$@"; do
         # Confirm deletion
         if [ "${YES#[Aa]}" = "$YES" ]; then
             echo -n "Delete $CHROOT? [a/y/N] " 1>&2
-            read YES
+            if [ -n "$CROUTON_EDIT_RESPONSE" ]; then
+                YES="$CROUTON_EDIT_RESPONSE"
+                echo "$YES" 1>&2
+            else
+                read YES
+            fi
             if [ "${YES#[AaYy]}" = "$YES" ]; then
                  error 2 "Aborting deletion of $CHROOT"
             fi
         fi
         # Delete the chroot
         echo -n "  Deleting $CHROOT..." 1>&2
-        rm -rvf --one-file-system "$CHROOT" | spinner 1000
+        spinner 1000 rm -rvf --one-file-system "$CHROOT"
         echo "Finished deleting $CHROOT" 1>&2
         continue
     fi
@@ -207,16 +239,18 @@ for NAME in "$@"; do
     # Backup the chroot
     if [ -n "$BACKUP" ]; then
         dest="$TARBALL"
+        date="`date '+%Y%m%d-%H%M'`"
         if [ -z "$dest" -o -d "$TARBALL" ]; then
-            dest="$TARBALL$NAME-`date '+%Y%m%d-%H%M'`.tar"
+            dest="$TARBALL$NAME-$date.tar"
             # Only compress if it's not encrypted (it'd be a waste of time)
             if [ ! -f "$CHROOT/.ecryptfs" ]; then
                 dest="$dest.gz"
             fi
         fi
         echo -n "  Backing up $CHROOT to $dest..." 1>&2
-        tar --checkpoint=100 --checkpoint-action=exec=echo --one-file-system \
-            -caf "$dest" -C "$CHROOTS" "$NAME" | spinner
+        spinner 1 tar --checkpoint=100 --checkpoint-action=exec=echo \
+            --one-file-system -V "crouton:backup.${date%-*}${date#*-}-$NAME" \
+            -caf "$dest" -C "$CHROOTS" "$NAME"
         echo "Finished backing up $CHROOT to $dest" 1>&2
     fi
 
@@ -233,7 +267,7 @@ for NAME in "$@"; do
                     continue
                 fi
                 # Confirm it's a tarball
-                if ! tar --test-label -f "$file" 2>/dev/null; then
+                if ! tar --test-label -f "$file" >/dev/null 2>&1; then
                     continue
                 fi
                 # Since * alphabetizes, always keep the last one
@@ -243,7 +277,7 @@ for NAME in "$@"; do
                 error 2 "Unable to find a tarball for $NAME. You can specify one with -f."
             fi
             echo "Found $src for restoring $NAME." 1>&2
-        elif ! tar --test-label -f "$src" 2>/dev/null; then
+        elif ! tar --test-label -f "$src" >/dev/null 2>&1; then
             error 2 "$src doesn't appear to be a valid tarball."
         fi
         if [ -n "$EXISTS" ]; then
@@ -254,13 +288,14 @@ for NAME in "$@"; do
         fi
         echo -n "  Restoring $src to $CHROOT..." 1>&2
         mkdir -p "$CHROOT"
-        tar --checkpoint=200 --checkpoint-action=exec=echo --one-file-system \
-            -xaf "$src" -C "$CHROOT" --strip-components=1 | spinner
+        spinner 1 tar --checkpoint=200 --checkpoint-action=exec=echo \
+            --one-file-system -xaf "$src" -C "$CHROOT" --strip-components=1
         echo "Finished restoring $src to $CHROOT" 1>&2
     fi
 
     # Update the keyfile
     if [ -n "$KEYFILE" ]; then
+        newkeyfile="$KEYFILE"
         # Find the current keyfile
         oldkeyfile="$CHROOT/.ecryptfs"
         if [ -f "$oldkeyfile" ]; then
@@ -269,36 +304,41 @@ for NAME in "$@"; do
                 oldkeyfile="$header"
             fi
         fi
-        if [ "$KEYFILE" = '-' ]; then
-            KEYFILE="$CHROOT/.ecryptfs"
+        if [ "$newkeyfile" = '-' ]; then
+            newkeyfile="$CHROOT/.ecryptfs"
         fi
-        if [ "${KEYFILE#/}" = "$KEYFILE" ]; then
-            KEYFILE="$PWD/$KEYFILE"
+        if [ "${newkeyfile#/}" = "$newkeyfile" ]; then
+            newkeyfile="$PWD/$newkeyfile"
         fi
-        if [ -d "$KEYFILE" -o ! "${KEYFILE%/}" = "$KEYFILE" ]; then
-            KEYFILE="${KEYFILE%/}/$NAME"
+        if [ -d "$newkeyfile" -o ! "${newkeyfile%/}" = "$newkeyfile" ]; then
+            newkeyfile="${newkeyfile%/}/$NAME"
         fi
         oldkeyfile="`readlink -m "$oldkeyfile"`"
-        keyfilecanon="`readlink -m "$KEYFILE"`"
+        keyfilecanon="`readlink -m "$newkeyfile"`"
         if [ ! -f "$oldkeyfile" ]; then
             # If there is no old keyfile, make sure we've requested encryption.
             if [ -z "$ENCRYPT" ]; then
                 error 1 "Old key file not found"
             fi
         elif [ ! "$oldkeyfile" = "$keyfilecanon" ]; then
-            # Write the new keyfile before removing the old.
-            if ! mkdir -p "`dirname "$KEYFILE"`"; then
-                error 1 "Unable to create directory for $KEYFILE"
+            chrootecryptfsfile="`readlink -m "$CHROOT/.ecryptfs"`"
+            # Don't clobber a file already there
+            if [ -e "$newkeyfile" -a "$newkeyfile" != "$chrootecryptfsfile" ]; then
+                error 1 "Encryption key file $newkeyfile already exists. Refusing to overwrite!"
             fi
-            echo "Moving key file from $oldkeyfile to $KEYFILE" 1>&2
-            (echo; tail -n+2 "$oldkeyfile") > "$KEYFILE"
+            # Write the new keyfile before removing the old.
+            if ! mkdir -p "`dirname "$newkeyfile"`"; then
+                error 1 "Unable to create directory for $newkeyfile"
+            fi
+            echo "Moving key file from $oldkeyfile to $newkeyfile" 1>&2
+            (echo; tail -n+2 "$oldkeyfile") > "$newkeyfile"
             # Remove old keyfile before writing .ecryptfs, as it may be the same
             rm -f "$oldkeyfile"
-            if [ ! "`readlink -m "$CHROOT/.ecryptfs"`" = "$KEYFILE" ]; then
-                echo "$KEYFILE" > "$CHROOT/.ecryptfs"
+            if [ "$chrootecryptfsfile" != "$newkeyfile" ]; then
+                echo "$newkeyfile" > "$CHROOT/.ecryptfs"
             fi
         elif [ -z "$ENCRYPT$MOVE" ]; then
-            echo "Keyfile is already located at $KEYFILE" 1>&2
+            echo "Keyfile is already located at $newkeyfile" 1>&2
         fi
     fi
 
@@ -342,7 +382,12 @@ for NAME in "$@"; do
             # Confirm long operation
             if [ "${YES#[Aa]}" = "$YES" ]; then
                 echo -n "Are you sure you want to continue? [a/y/N] " 1>&2
-                read YES
+                if [ -n "$CROUTON_EDIT_RESPONSE" ]; then
+                    YES="$CROUTON_EDIT_RESPONSE"
+                    echo "$YES" 1>&2
+                else
+                    read YES
+                fi
                 if [ "${YES#[AaYy]}" = "$YES" ]; then
                      error 2 "Aborting move of $CHROOT"
                 fi
@@ -351,10 +396,10 @@ for NAME in "$@"; do
                 error 1 "Unable to create directory for $target"
             fi
             echo -n "  Copying to $target..." 1>&2
-            cp -av --one-file-system "$CHROOT" "$target" | spinner 200
+            spinner 200 cp -av --one-file-system "$CHROOT" "$target"
             echo "Finished copying to $target" 1>&2
             echo -n "  Deleting old $CHROOT..." 1>&2
-            rm -rfv --one-file-system "$CHROOT" | spinner 1000
+            spinner 1000 rm -rfv --one-file-system "$CHROOT"
             echo "Finished deleting old $CHROOT" 1>&2
         else
             if ! mkdir -p "`dirname "$target"`"; then
diff --git a/host-bin/enter-chroot b/host-bin/enter-chroot
--- a/host-bin/enter-chroot
+++ b/host-bin/enter-chroot
@@ -3,9 +3,11 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+set -e
+
 APPLICATION="${0##*/}"
 BACKGROUND=''
-BINDIR="`dirname "$0"`"
+BINDIR="`dirname "\`readlink -f "$0"\`"`"
 CHROOTS="`readlink -f "$BINDIR/../chroots"`"
 KEYFILE=''
 LOGIN=''
@@ -37,6 +39,21 @@ Options:
 
 # Common functions
 . "$BINDIR/../installer/functions"
+
+# Safely launch a command ($*) via /bin/sh within the chroot as the root user.
+chrootcmd() {
+    # env may be overridden when running in the background; don't let it fork.
+    local ret=0 oldtrap="$TRAP"
+    TRAP=''
+    env -i chroot "$CHROOT" su -s '/bin/sh' -c "$*" - root || ret=$?
+    local pid="$!"
+    # $pid might not be set if env has not been redefined yet
+    if [ -n "$BACKGROUND" ] && [ -n "$pid" ]; then
+        wait "$pid" || ret=$?
+    fi
+    TRAP="$oldtrap"
+    return "$ret"
+}
 
 # Process arguments
 while getopts 'bc:k:ln:t:u:x' f; do
@@ -104,10 +121,22 @@ elif [ -n "$TARGET" ]; then
     fi
 fi
 
+# Avoid kernel panics due to slow I/O
+disablehungtask
+
+# Enable control of framebuffer compression (if used) by video users
+for fbc in '/sys/kernel/debug/dri/0/'*fbc*; do :; done
+if [ -f "$fbc" ] && ! grep -q 'disabled per module param' "$fbc"; then
+    fbc='/sys/module/i915/parameters/i915_enable_fbc'
+    chgrp video "$fbc"
+    chmod g+w "$fbc"
+fi
+
 # Make sure we always exit with echo on the tty.
-addtrap "stty echo 2>/dev/null || true"
+addtrap "stty echo 2>/dev/null"
 
 # Mount the chroot and update our CHROOT path
+CHROOTSRC="$CHROOTS/$NAME"
 if [ -n "$KEYFILE" ]; then
     CHROOT="`sh -e "$BINDIR/mount-chroot" \
                                      -k "$KEYFILE" -p -c "$CHROOTS" "$NAME"`"
@@ -116,7 +145,7 @@ else
 fi
 
 if [ ! "$NOLOGIN" = 2 ]; then
-    echo "Entering $CHROOT..." 1>&2
+    echo "Entering $CHROOTSRC..." 1>&2
 fi
 
 # In disk full situations, mount-chroot can be empty. Good time to check sanity.
@@ -134,14 +163,16 @@ fi
 
 if [ -z "$CROUTON_NO_UNMOUNT" ]; then
     # Auto-unmount everything below and including the chroot upon exit
-    addtrap "sh -e '$BINDIR/unmount-chroot' -yc '$CHROOTS' '$NAME' || true"
+    addtrap "sh -e '$BINDIR/unmount-chroot' -yc '$CHROOTS' '$NAME'"
 fi
 
 # If our root is on an external disk we need to ensure USB device persistence is
 # enabled otherwise we will lose the file-system after a suspend event.
-if [ ! "${CHROOT#/media}" = "$CHROOT" ]; then
+if [ ! "${CHROOTSRC#/media}" = "$CHROOTSRC" ]; then
     for usbp in /sys/bus/usb/devices/*/power/persist; do
-        echo 1 > "$usbp"
+        if [ -e "$usbp" ]; then
+            echo 1 > "$usbp"
+        fi
     done
 fi
 
@@ -150,16 +181,30 @@ if [ -z "$NOLOGIN" -a -f "$CHROOT$SETUPSCRIPT" ]; then
     echo 'A chroot setup script still exists inside the chroot.' 1>&2
     echo 'The chroot may not be fully set up.' 1>&2
     response=''
-    if tty -s; then
-        echo -n 'Would you like to finish the setup? [Y/n] ' 1>&2
+    # A finished setup script will have permissions 500
+    if [ "`stat -c '%a' "$CHROOT$SETUPSCRIPT"`" != '500' ]; then
+        echo 'However, it appears the setup script is invalid.' 1>&2
+        response='d'
+    fi
+    if [ -t 0 -a -z "$response" ]; then
+        echo -n 'Would you like to finish the setup? [Y/n/d] ' 1>&2
         read response
     fi
-    if [ -z "$response" -o ! "${response#[Yy]}" = "$response" ]; then
+    if [ -z "$response" -o "${response#[Yy]}" != "$response" ]; then
         echo 'Preparing chroot environment...' 1>&2
-        CROUTON_NO_UNMOUNT=1 sh -e "$BINDIR/enter-chroot" \
-            -c "$CHROOTS" -n "$NAME" -xx
-        echo 'Setup completed. Entering chroot...' 1>&2
-    else
+        if CROUTON_NO_UNMOUNT=1 sh -e "$BINDIR/enter-chroot" \
+                -c "$CHROOTS" -n "$NAME" -xx; then
+            echo 'Setup completed. Entering chroot...' 1>&2
+            response=''
+        else
+            echo 'The chroot setup script may be broken. Your chroot is not fully configured.' 1>&2
+            response='d'
+        fi
+    fi
+    if [ "${response#[Dd]}" != "$response" ]; then
+        echo 'Removing the chroot setup script. You may want to update your chroot again.' 1>&2
+        rm -f "$CHROOT$SETUPSCRIPT"
+    elif [ -n "$response" ]; then
         echo 'Skipping setup. You will be prompted again next time.' 1>&2
     fi
 fi
@@ -168,7 +213,7 @@ fi
 passwd="$CHROOT/etc/passwd"
 if [ -z "$NOLOGIN" ]; then
     if [ ! -r "$passwd" ]; then
-        error 1 "$CHROOT doesn't appear to be a valid chroot."
+        error 1 "$CHROOTSRC doesn't appear to be a valid chroot."
     fi
     case "$USERNAME" in
     ''|*[!0-9]*)
@@ -189,39 +234,6 @@ if [ -z "$NOLOGIN" ]; then
     CHROOTSHELL="`awk -F: '$1=="'"$USERNAME"'"{print $NF; exit}' "$passwd"`"
 else
     CHROOTSHELL='/bin/sh'
-fi
-
-# Fix group numbers for critical groups to match Chromium OS. This is necessary
-# so that users have access to shared hardware, such as video and audio.
-gfile="$CHROOT/etc/group"
-if [ -f "$gfile" ]; then
-    for group in audio video usb:plugdev; do
-        hostgroup="${group%:*}"
-        chrootgroup="${group#*:}"
-        gid="`awk -F: '$1=="'"$hostgroup"'"{print $3; exit}' '/etc/group'`"
-        if [ -z "$gid" ]; then
-            echo "Couldn't find $hostgroup group in Chromium OS!" 1>&2
-            continue
-        fi
-        curgid="`awk -F: '$1=="'"$chrootgroup"'"{print $3; exit}' "$gfile"`"
-        if [ "$gid" = "$curgid" ]; then
-            continue
-        elif [ -z "$curgid" ]; then
-            echo "Couldn't find $chrootgroup group in chroot!" 1>&2
-            continue
-        fi
-        echo "Changing $chrootgroup GID from $curgid to $gid..." 1>&2
-        move="`awk -F: '$3=='"$gid"'{print $1; exit}' "$gfile"`"
-        if [ -n "$move" ]; then
-            ngid="$gid"
-            while grep -q ":$ngid:" "$gfile"; do
-                ngid="$((ngid+1))"
-            done
-            echo "Moving $move GID from $gid to $ngid..." 1>&2
-            sed -i "s/:$gid:/:$ngid:/" "$gfile"
-        fi
-        sed -i "s/:$curgid:/:$gid:/" "$gfile"
-    done
 fi
 
 # Save the chroot name to the chroot
@@ -288,9 +300,6 @@ bindmount() {
     mount --bind $bindopts "$1" "$target"
     if [ -n "$3" ]; then
         mount -i -o "remount,$3" "$target"
-        if [ -n "$4" ]; then
-            mount $4 "$target"
-        fi
     fi
 }
 
@@ -311,8 +320,6 @@ else
     firstrun='y'
 fi
 
-# Ensure the chroot is executable and writable by bind-mounting it to itself.
-bindmount "$CHROOT" / rw,dev,exec,suid --make-unbindable
 bindmount /dev
 bindmount /dev/pts
 bindmount /dev/shm
@@ -324,6 +331,7 @@ tmpfsmount /var/run 'noexec,nosuid,mode=0755,size=10%'
 tmpfsmount /var/run/lock 'noexec,nosuid,nodev,size=5120k'
 bindmount /var/run/dbus /var/host/dbus
 bindmount /var/run/shill /var/host/shill
+bindmount /var/run/cras /var/host/cras
 bindmount /var/lib/timezone /var/host/timezone
 for m in /lib/modules/*; do
     if [ -d "$m" ]; then
@@ -337,11 +345,14 @@ ln -sfT /dev/shm "`fixabslinks '/var/run'`/shm"
 # Add a /run/udev symlink for later versions of udev
 ln -sfT /dev/.udev "`fixabslinks '/var/run'`/udev"
 
+# Add a /var/host/cras symlink for CRAS clients
+ln -sfT /var/host/cras "`fixabslinks '/var/run'`/cras"
+
 # Bind-mount /media, specifically the removable directory
 destmedia="`fixabslinks '/var/host/media'`"
-if [ -d "$CHROOT/media" ] && ! mountpoint -q "$destmedia"; then
+if ! mountpoint -q "$destmedia"; then
     mount --make-shared /media
-    mkdir -p "$destmedia"
+    mkdir -p "$destmedia" "$CHROOT/media"
     ln -sf "/var/host/media/removable" "$CHROOT/media/"
     mount --rbind /media "$destmedia"
 fi
@@ -352,22 +363,65 @@ if [ -z "$NOLOGIN" -a -n "$CHROOTHOME" -a -d "$localdownloads" ]; then
     bindmount "$localdownloads" "$CHROOTHOME/Downloads" exec
 fi
 
+# For test machines with low entropy, bind mount /dev/urandom to /dev/random
+if [ -n "$CROUTON_WEAK_RANDOM" ]; then
+    mount --bind "$CHROOT/dev/urandom" "$CHROOT/dev/random"
+fi
+
+# Fix group numbers for critical groups to match Chromium OS. This is necessary
+# so that users have access to shared hardware, such as video and audio.
+gfile="$CHROOT/etc/group"
+if [ -f "$gfile" ]; then
+    for group in audio:hwaudio cras:audio cdrom disk floppy i2c input lp \
+                 serial tape tty usb:plugdev uucp video; do
+        hostgroup="${group%:*}"
+        chrootgroup="${group#*:}"
+        gid="`awk -F: '$1=="'"$hostgroup"'"{print $3; exit}' '/etc/group'`"
+        if [ -z "$gid" ]; then
+            echo "Couldn't find $hostgroup group in Chromium OS!" 1>&2
+            continue
+        fi
+        curgid="`awk -F: '$1=="'"$chrootgroup"'"{print $3; exit}' "$gfile"`"
+        if [ "$gid" = "$curgid" ]; then
+            continue
+        elif [ -z "$curgid" ]; then
+            echo "Creating $chrootgroup group with GID $gid..." 1>&2
+            groupcmd=groupadd
+        else
+            echo "Changing $chrootgroup GID from $curgid to $gid..." 1>&2
+            groupcmd=groupmod
+        fi
+        move="`awk -F: '$3=='"$gid"'{print $1; exit}' "$gfile"`"
+        if [ -n "$move" ]; then
+            ngid="$gid"
+            while grep -q ":$ngid:" "$gfile"; do
+                ngid="$((ngid+1))"
+            done
+            echo "Moving $move GID from $gid to $ngid..." 1>&2
+            chrootcmd groupmod -g "$ngid" "$move"
+        fi
+        chrootcmd "$groupcmd" -g "$gid" "$chrootgroup"
+    done
+fi
+
 # To run silently, we override the env command to launch a background process,
 # and move the trap code to happen there.
 if [ -n "$BACKGROUND" ]; then
     env() {
-        local stdin=''
-        [ ! -t 0 ] && stdin="`readlink -m /dev/stdin`"
-        (
+        # Shuffle FDs around to preserve stdin
+        { (
             trap '' INT HUP
             trap "$TRAP" 0
-            [ -n "$stdin" ] && exec < "$stdin"
-            [ -t 1 ] && exec  > /dev/null
-            [ -t 2 ] && exec 2> /dev/null
+            exec 0<&9 9<&-
+            [ -t 0 ] && exec < /dev/null
+            [ -t 1 ] && exec > /dev/null
+            [ -t 2 ] && exec 2>&1
             /usr/bin/env "$@"
-        ) &
+        ) & } 9<&0
     }
 fi
+
+ret=0
 
 # Launch the system dbus unless we are entering a basic shell.
 if [ ! "$NOLOGIN" = 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
@@ -377,7 +431,7 @@ if [ ! "$NOLOGIN" = 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
     dbususer="`echo "cat /busconfig/user/text()" \
         | xmllint --shell "$CHROOT/etc/dbus-1/system.conf" 2>/dev/null \
         | grep '^[a-z][-a-z0-9_]*$' || true`"
-    env -i chroot "$CHROOT" su -s '/bin/sh' -c "
+    chrootcmd "
         if ! hash dbus-daemon 2>/dev/null; then
             exit 0
         fi
@@ -394,11 +448,14 @@ if [ ! "$NOLOGIN" = 1 ] && grep -q '^root:' "$passwd" 2>/dev/null; then
         dbususer="`id -un "$dbususer" 2>/dev/null || echo "messagebus"`"
         dbusgrp="`id -gn "$dbususer" 2>/dev/null || echo "messagebus"`"
         chown "$dbususer:$dbusgrp" /var/run/dbus
-        dbus-daemon --system --fork' - root
+        exec dbus-daemon --system --fork' || ret=$?
+    if [ ! "$ret" = 0 ]; then
+        echo "WARNING: starting chroot system dbus daemon failed with code $ret" 1>&2
+        ret=0
+    fi
 fi
 
 # Start the chroot and any specified command
-ret=0
 if [ -n "$NOLOGIN" ]; then
     env -i TERM="$TERM" chroot "$CHROOT" "$@" || ret=$?
     # Handle the return value when running the setup script.
@@ -415,8 +472,7 @@ if [ -n "$NOLOGIN" ]; then
 else
     # Run rc.local
     if [ -n "$firstrun" -a -x "$CHROOT/etc/rc.local" ]; then
-        env -i chroot "$CHROOT" su -s '/bin/sh' -c \
-            'exec /etc/rc.local >/dev/null 2>/dev/null </dev/null' - root \
+        chrootcmd 'exec /etc/rc.local >/dev/null 2>/dev/null </dev/null' \
             || ret=$?
         if [ ! "$ret" = 0 ]; then
             echo "WARNING: /etc/rc.local failed with code $ret" 1>&2
@@ -440,7 +496,7 @@ fi
 
 # We don't want to trap for this proccess if we're running in the background
 if [ -n "$BACKGROUND" ]; then
-    trap - INT HUP 0
+    settrap ''
 fi
 
 # Cleanup all happens in the exit trap
diff --git a/host-bin/unmount-chroot b/host-bin/unmount-chroot
--- a/host-bin/unmount-chroot
+++ b/host-bin/unmount-chroot
@@ -3,15 +3,19 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+set -e
+
 APPLICATION="${0##*/}"
 ALLCHROOTS=''
-CHROOTS="`readlink -f "\`dirname "$0"\`/../chroots"`"
+BINDIR="`dirname "\`readlink -f "$0"\`"`"
+CHROOTS="`readlink -f "$BINDIR/../chroots"`"
 EXCLUDEROOT=''
 FORCE=''
 PRINT=''
 SIGNAL='TERM'
 TRIES=5
 YES=''
+ROOT='/var/run/crouton'
 
 USAGE="$APPLICATION [options] name [...]
 
@@ -124,6 +128,9 @@ checkusage() {
 
 # If we specified all chroots, bring in all chroots.
 if [ -n "$ALLCHROOTS" ]; then
+    if [ ! -d "$CHROOTS" ]; then
+        error 1 "$CHROOTS not found."
+    fi
     set -- "$CHROOTS/"*
 fi
 
@@ -137,34 +144,53 @@ fixabslinks() {
     echo "$p"
 }
 
-# Unmount each chroot
-ret=0
-for NAME in "$@"; do
-    if [ -z "$NAME" ]; then
-        continue
-    fi
-
-    NAME="${NAME#"$CHROOTS/"}"
+# Unmount the specified chroot $1
+# sets oldstyle if the chroot was unmounted in an old location.
+# if oldstyle is set upon entry, skips the check for old-style mounts.
+unmount() {
+    NAME="${1#"$CHROOTS/"}"
 
     # Check for existence
     CHROOT="$CHROOTS/$NAME"
     if [ ! -d "$CHROOT" ]; then
-        echo "$CHROOT not found." 1>&2
-        ret=1
-        continue
+        if [ -z "$ALLCHROOTS" ]; then
+            echo "$CHROOT not found." 1>&2
+            ret=1
+        fi
+        return 0
     fi
 
-    # Switch to the unencrypted mount for encrypted chroots.
-    if [ -f "$CHROOT/.ecryptfs" ]; then
-        CHROOT="$CHROOTS/.secure/$NAME"
+    # Switch to the true mount point, but sort of support old-style mounted
+    # chroots with minimal false-positives to ease transition. Don't unmount
+    # old-style twice in a row, though.
+    CHROOTSRC="$CHROOT"
+    oldencr="$CHROOTS/.secure/$NAME"
+    if mountpoint -q "$oldencr" \
+            && [ -d "$oldencr/etc/crouton" -a -z "$oldstyle" ]; then
+        # Old encrypted chroots
+        oldstyle='y'
+        CHROOT="$oldencr"
+        echo "$CHROOTSRC appears to be mounted in $CHROOT" 1>&2
+    elif mountpoint -q "$CHROOT" \
+            && [ -d "$CHROOT/etc/crouton" -a -z "$oldstyle" ]; then
+        # Keep the chroot the same
+        oldstyle='y'
+        echo "$CHROOTSRC appears to be mounted in place" 1>&2
+    else
+        oldstyle=''
+        CHROOT="$ROOT/${CHROOT#/}"
+        if [ ! -d "$CHROOT" ]; then
+            # Not mounted
+            return 0
+        fi
     fi
 
     base="`readlink -f "$CHROOT"`"
 
     if ! checkusage "$base"; then
-        echo "Not unmounting $CHROOT as another instance is using it." 1>&2
+        echo "Not unmounting $CHROOTSRC as another instance is using it." 1>&2
         ret=1
-        continue
+        return 0
     fi
 
     # Kill the chroot's system dbus if one is running; failure is fine
@@ -182,9 +208,9 @@ for NAME in "$@"; do
     # Unmount all mounts
     ntries=0
     if [ -z "$EXCLUDEROOT" ]; then
-        echo "Unmounting $CHROOT..." 1>&2
+        echo "Unmounting $CHROOTSRC..." 1>&2
     else
-        echo "Pruning $CHROOT mounts..." 1>&2
+        echo "Pruning $CHROOTSRC mounts..." 1>&2
     fi
     baseesc="`echo "$base" | sed 's= =//=g'`"
 
@@ -210,28 +236,37 @@ for NAME in "$@"; do
         mount --make-rslave "$media"
     fi
 
-    while ! sed "s=\\\\040=//=g" /proc/mounts | cut -d' ' -f2 \
-              | filter | sed 's=//= =g' | xargs --no-run-if-empty -d '
+    # Some /proc/mounts entries may end with \040(deleted), in that case, try to
+    # umount them with and without the suffix (in the unlikely case the mount
+    # point actually ends with ' (deleted)')
+    while ! sed "s=\\\\040=//=g" /proc/mounts | cut -d' ' -f2 | filter \
+              | sed -e 's=//= =g;s/^\(\(.*\) (deleted)\)$/\1\n\2/' \
+              | xargs --no-run-if-empty -d '
 ' -n 50 umount 2>/dev/null; do
         if [ "$ntries" -eq "$TRIES" ]; then
             # Send signal to all processes running under the chroot
             # ...but confirm first.
             printonly=''
             if [ "${YES#[Aa]}" = "$YES" ]; then
-                echo -n "Failed to unmount $CHROOT. Kill processes? [a/k/y/p/N] " 1>&2
-                read YES
+                echo -n "Failed to unmount $CHROOTSRC. Kill processes? [a/k/y/p/N] " 1>&2
+                if [ -n "$CROUTON_UNMOUNT_RESPONSE" ]; then
+                    YES="$CROUTON_UNMOUNT_RESPONSE"
+                    echo "$YES" 1>&2
+                else
+                    read YES
+                fi
                 if [ ! "${YES#[Kk]}" = "$YES" ]; then
                     SIGNAL='KILL'
                 elif [ ! "${YES#[Pp]}" = "$YES" ]; then
                     printonly=y
                 elif [ "${YES#[AaYy]}" = "$YES" ]; then
-                    echo "Skipping unmounting of $CHROOT" 1>&2
+                    echo "Skipping unmounting of $CHROOTSRC" 1>&2
                     ret=1
                     break
                 fi
             fi
             if [ -z "$printonly" ]; then
-                echo "Sending SIG$SIGNAL to processes under $CHROOT..." 1>&2
+                echo "Sending SIG$SIGNAL to processes under $CHROOTSRC..." 1>&2
             fi
             for root in /proc/*/root; do
                 if [ ! -r "$root" ] \
@@ -266,7 +301,7 @@ for NAME in "$@"; do
         fi
         sleep 1
         if ! checkusage "$base"; then
-            echo "Aborting unmounting $CHROOT as another instance has begun using it." 1>&2
+            echo "Aborting unmounting $CHROOTSRC as another instance has begun using it." 1>&2
             ret=1
             break
         fi
@@ -274,13 +309,29 @@ for NAME in "$@"; do
 
     # More sync for more safety
     sync
+}
+
+# Unmount each chroot
+ret=0
+for NAME in "$@"; do
+    if [ -z "$NAME" ]; then
+        continue
+    fi
+    oldstyle=''
+    unmount "$NAME"
+    # If we unmounted old-style, do it again in case the new-style was also mounted.
+    if [ -n "$oldstyle" ]; then
+        unmount "$NAME"
+    fi
 done
 
 # Re-disable USB persistence (the Chromium OS default) if we no longer
 # have chroots running with a root in removable media
-if checkusage /media; then
+if checkusage "$ROOT/media"; then
     for usbp in /sys/bus/usb/devices/*/power/persist; do
-        echo 0 > "$usbp"
+        if [ -e "$usbp" ]; then
+            echo 0 > "$usbp"
+        fi
     done
 fi
 
diff --git a/installer/functions b/installer/functions
--- a/installer/functions
+++ b/installer/functions
@@ -28,11 +28,11 @@ installscript() {
         # This should never happen.
         error 1 "Unable to find common functions file."
     fi
-    sed -e "${3:-;}" "$src" | awk '/^\. .*\/installer\/functions/ {
+    awk '/^\. .*\/installer\/functions/ {
         system("'"awk 'ok; !ok && /^###/ {ok=1}' '$thisfile'"'");
         next
     }
-    1' > "$dst"
+    1' "$src" | sed -e "${3:-;}" > "$dst"
 }
 
 ### Everything after this line will be statically inserted into scripts.
@@ -46,12 +46,13 @@ error() {
 }
 
 # Setup trap ($1) in case of interrupt or error.
+# Traps explicitly do not exit on command error.
 # Traps are first disabled to avoid executing clean-up commands twice.
 # In the case of interrupts, exit is called to avoid the script continuing.
 # $1 must either be empty or end in a semicolon.
 settrap() {
-    trap "trap - INT HUP 0; $1 exit 2" INT HUP
-    trap "trap - INT HUP 0; $1" 0
+    trap "set +e; trap - INT HUP TERM 0; $1 exit 2" INT HUP TERM
+    trap "set +e; trap - INT HUP TERM 0; $1" 0
 }
 
 # Prepend a command to the existing $TRAP
@@ -65,4 +66,80 @@ addtrap() {
 undotrap() {
     TRAP="$OLDTRAP"
     settrap "$TRAP"
+}
+
+# Compares $RELEASE to the specified releases, assuming $DISTRODIR/releases is
+# sorted oldest to newest. Every two parameters are considered criteria that are
+# ORed together. The first parameter is the comparator, as provided to "test".
+# The second parameter is the release to compare to. A comparison against a
+# release from a different distro always fails. Since either $DISTRODIR/releases
+# has to be readable or the release list has to be embedded, and RELEASE has to
+# be set properly, this function should only be used in the context of targets.
+# Returns non-zero if the release doesn't match
+# Example:  release -ge quantal -ge wheezy
+release() {
+    if [ "$(($# % 2))" -ne 0 ]; then
+        error 3 "invalid parameters to release(): $*"
+    fi
+    # Load up the list of releases; this will be replaced with a literal list
+    local releases="`cat "$DISTRODIR/releases" 2>/dev/null`"
+    if [ -z "$releases" ]; then
+        error 3 "list of releases for $DISTRO not found"
+    fi
+    # End-of-word regex for awk
+    local eow='([^a-z]|$)'
+    local relnum="`echo "$releases" | awk "/^$RELEASE$eow/ {print NR; exit}"`"
+    if [ -z "$relnum" ]; then
+        error 3 "$RELEASE not found in $DISTRO"
+    fi
+    while [ "$#" -ge 2 ]; do
+        local cmp="`echo "$releases" | awk "/^$2$eow/ {print NR; exit}"`"
+        if [ -n "$cmp" ] && test "$relnum" "$1" "$cmp"; then
+            return 0
+        fi
+        shift 2
+    done
+    return 1
+}
+
+# Large writes to slow devices (e.g. SD card or USB stick) can cause a task to
+# be stuck for longer than 120 seconds, which triggers a kernel panic (and an
+# immediate reboot). Instead of disabling the timeout altogether, we just make
+# sure the kernel does not panic (this is the default configuration of a vanilla
+# kernel). See crbug.com/260955 for details.
+disablehungtask() {
+    echo 0 > /proc/sys/kernel/hung_task_panic
+}
+
+# Run an awk program, without buffering its output.
+# unbuffered_awk 'program' [argument ...]
+# In the awk code, all "print" calls must be replaced by "output"
+#
+# - Detects whether to run mawk or gawk (mawk is preferred as it is faster),
+# - Prepends the definition of the "output" function to the awk program
+# - Run the modified awk program.
+# mawk needs '-W interactive' to flush the output properly (fflush does not
+# work as documented, but apparently this behaviour is intentional, see
+# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593504).
+# Furthermore, fflush is not POSIX so we cannot use any other awk flavor.
+unbuffered_awk() {
+    local cmd
+    if hash mawk 2>/dev/null; then
+        cmd="mawk -W interactive"
+    elif hash gawk 2>/dev/null; then
+        cmd="gawk"
+    else
+        echo "Cannot find mawk or gawk." 1>&2
+        return 1
+    fi
+
+    local program="$1"
+    shift
+
+    $cmd '
+    function output(s) {
+        print s
+        fflush()
+    }
+    '"$program" "$@"
 }
