Dead code removal.

diff --git a/chroot-bin/setres b/chroot-bin/setres
--- a/chroot-bin/setres
+++ b/chroot-bin/setres
@@ -85,39 +85,6 @@ else
     xrandr --rmmode "$name" 2>/dev/null || true
 fi
 
-# Setting a custom mode failed, fall back on best match
-
-# This assumes modes have "canonical" names, in the form "<w>x<h>[_<r>]"
-res="`xrandr | awk '
-    function abs(x) { return x > 0 ? x : -x }
-    BEGIN {
-        tw='"$x"'
-        th='"$y"'
-        oversize_penalty = 1000000
-    }
-    $1 ~ /[0-9]+x[0-9]+/ {
-        res = $1; sub(/_[0-9]+/, "", res)
-        w = res; sub(/x[0-9]*/, "", w); w = int(w)
-        h = res; sub(/[0-9]*x/, "", h); h = int(h)
-        score = abs(tw-w) + abs(th-h)
-        if (w > tw) score += oversize_penalty
-        if (h > th) score += oversize_penalty
-        if (!cmode || score < cscore) {
-            cmode = $1
-            cscore = score
-        }
-    }
-    END {
-        if (!cmode) exit 1
-        print cmode
-    }
-'`"
-
-if [ -z "$res" ]; then
-   echo "Cannot find resolution" 1>&2
-   exit 1
-fi
-
-xrandr -s "$res" 2>/dev/null
-echo "$res"
-exit 0
+# Probably xorg-dummy got overwritten. Recommend an update.
+echo "Failed to set custom resolution. Update your chroot and try again." 1>&2
+exit 1
