debootstrap: Print debootstrap.log on error
Makes debugging a tiny bit easier.

diff --git a/installer/ubuntu/bootstrap b/installer/ubuntu/bootstrap
--- a/installer/ubuntu/bootstrap
+++ b/installer/ubuntu/bootstrap
@@ -71,7 +71,11 @@ fi
 
 # Grab the release and drop it into the subdirectory
 echo 'Downloading bootstrap files...' 1>&2
-PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" $FAKEROOT \
-    "$tmp/debootstrap" --foreign --extractor='ar' --arch="$ARCH" \
-    "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2
+if ! PATH="$newpath" DEBOOTSTRAP_DIR="$tmp" $FAKEROOT \
+        "$tmp/debootstrap" --foreign --extractor='ar' --arch="$ARCH" \
+        "$RELEASE" "$tmp/$subdir" "$MIRROR" 1>&2; then
+    echo "debootstrap error log:" 1>&2
+    tail -n 3 "$tmp/$subdir/debootstrap/debootstrap.log" 1>&2 || true
+    error 1 'Failed to run debootstrap.'
+fi
 
