ubuntu/bootstrap: Patch debootstrap so that it retries downloads
It retries 10 times, which is arguably too many times, but that
should be better than the current behaviour.

Applies cleanly on git HEAD and debootstrap 1.0.61. I will try to
upstream that modification.

Test:
 - Start installer, regularly run `sudo pkill wget` and check
   that the installation still proceeds.

diff --git a/installer/ubuntu/bootstrap b/installer/ubuntu/bootstrap
--- a/installer/ubuntu/bootstrap
+++ b/installer/ubuntu/bootstrap
@@ -31,6 +31,19 @@ Check your internet connection or proxy settings and try again.'
     fi
 fi
 
+# Patch debootstrap so that it retries downloading packages
+awk '
+    t == 2 && /-z \"\$checksum\"/ { sub(/\$checksum/, "$checksum$failed"); t=0 }
+    t == 1 { sub(/if \[/, "elif ["); t=2 }
+    /if ! just_get \"\$from\" \"\$dest2\"; then continue 2; fi/ {
+        sub(/if !/, "failed=; if !")
+        sub(/continue 2; fi/, "failed=y")
+        t=1
+    }
+    1
+' "$tmp/functions" > "$tmp/functions.new"
+mv "$tmp/functions.new" "$tmp/functions"
+
 # Add the necessary debootstrap executables
 newpath="$PATH:$tmp"
 cp "$INSTALLERDIR/$DISTRO/ar" "$INSTALLERDIR/$DISTRO/pkgdetails" "$tmp/"
