Gentoo: Support switching profiles. Add support for kde and gnome targets.
Fix.

diff --git a/installer/gentoo/prepare b/installer/gentoo/prepare
--- a/installer/gentoo/prepare
+++ b/installer/gentoo/prepare
@@ -49,7 +49,7 @@ keyword_package() {
     # Check if the keyword is set for this package and if not, set it
     if ! grep -q -e "^$1[[:space:]]" -e "^$1$" -e "^<=$1-$3" "$PDIR/crouton"; then
         echo "# Added keywords for crouton target $2" >> "$PDIR/crouton"
-	if [ -z $3 ]; then
+	if [ -z "$3" ]; then
             echo "$1" >> "$PDIR/crouton"
 	else
             echo "<=$1-$3" >> "$PDIR/crouton"
@@ -91,6 +91,20 @@ set_use_expand() {
             sed -i -e "s|$1=\"\(.*\)\"|$1=\"\1 $2\"|" "$PM"
         fi
     fi
+}
+
+# Switch the system profile
+# Usage: set_profile <profile keyword to search for, can include regex>
+set_profile() {
+    # Get the profile number to switch to
+    local NEW_PROFILE="$(eselect profile list | awk '{ print $2 }' | grep "$1")"
+    if [ -z "$NEW_PROFILE" ]; then
+       echo "ERROR: Unable to find a profile that matches $1." 2>&1
+       exit 99
+    fi
+
+    # Set the profile
+    eselect profile set "$NEW_PROFILE"
 }
 
 # install_dist: see install() in prepare.sh for details.
diff --git a/targets/kde b/targets/kde
--- a/targets/kde
+++ b/targets/kde
@@ -1,5 +1,5 @@
 #!/bin/sh -e
-# Copyright (c) 2016 The crouton Authors. All rights reserved.
+# Copyright (c) 2017 The crouton Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 REQUIRES='x11'
@@ -9,11 +9,25 @@ CHROOTBIN='crouton-noroot startkde'
 . "${TARGETSDIR:="$PWD"}/common"
 
 ### Append to prepare.sh:
-install --minimal kde-baseapps kde-runtime plasma-desktop pulseaudio \
+if [ "${DISTROAKA:-"$DISTRO"}" = 'gentoo' ]; then
+    # Check profile to see if we're already on a KDE profile
+    if eselect profile show | grep -q gnome; then
+       echo "ERROR: On Gentoo, 'gnome' target is incompatible with kde." 2>&1
+       exit 99
+    fi
+
+    # Set the profile
+    set_profile "plasma$"
+
+    # Install kde
+    install kde-meta
+else
+    install --minimal kde-baseapps kde-runtime plasma-desktop pulseaudio \
         -- network-manager
 
-if release -lt xenial -lt kali -lt stretch; then
-    install --minimal kde-workspace
+    if release -lt xenial -lt kali -lt stretch; then
+        install --minimal kde-workspace
+    fi
 fi
 
 TIPS="$TIPS
