Rebased branch

diff --git a/installer/gentoo/prepare b/installer/gentoo/prepare
--- a/installer/gentoo/prepare
+++ b/installer/gentoo/prepare
@@ -24,48 +24,39 @@ install_dist() {
         pkgs="$pkgs $1"
         shift
     done
-    emerge --autounmask-write --newuse -qu --jobs=$NJOBS $params $pkgs  
-    dispatch-conf
+#    emerge --autounmask-write --newuse -qu --jobs=$NJOBS $params $pkgs  
+#    dispatch-conf
     emerge --newuse -qu --jobs=$NJOBS $params $pkgs 
 }
 
 
 # install_pkg_dist: see install_pkg() in prepare.sh for details.
 install_pkg_dist() {
-    local params=''
-    if [ "$1" = '--minimal' ]; then
-        params='--oneshot'
-        shift
-    fi
-#    if [ ! "$#" = 0 ]; then
-#        dpkg --force-depends -i "$@"
-#    fi
-#    apt-get -fy $params install
+    error 1 'ERROR: install_pkg_dist does not make sense for Gentoo'
 }
 
 
 # remove_dist: see remove() in prepare.sh for details.
 remove_dist() {
     emerge -C "$@"
+    emerge --depclean
+    revdep-rebuild
 }
 
 
 # list_uninstalled_dist: see list_uninstalled() in prepare.sh for details.
+#I'm not sure this make sense for Gentoo
 list_uninstalled_dist() {
-    local suffix="$1" pkg
-    shift
     for pkg in "$@"; do
-        if ! dpkg-query -s "$pkg" 2>/dev/null >/dev/null; then
-            echo -n "$pkg$suffix "
+        if ! `genlop -i "$pkg" | grep -q "date"` 2>/dev/null; then
+            echo -n "$pkg "
         fi
     done
 }
-
-
 # Bootstrap portage
 emerge --sync
 #Set MAKEOPTS and jobs based on processor cores
-if ! `/bin/grep -q 'MAKEOPTS' /etc/portage/make.conf`; then
+if ! grep -q 'MAKEOPTS' '/etc/portage/make.conf' 2>/dev/null; then
     echo "MAKEOPTS=\"-j$NJOBS\"" >> /etc/portage/make.conf
 fi
 
