tests: Split test runs by release, and retry as needed.
When `$release` is blank, the tests output a list of supported
releases, that is intersected with `$SUPPORTED_RELEASES`. Also,
`all` indicates that all releases are supported, and `default`
indicates that only a default release should be tested.

This allows to retry tests when needed, because of mirror issues.

Other keys features:
 - Randomized test order
 - Retry with a different release on default tests
 - Always run 3 jobs in parallel, we are usually not CPU-bound
   (also, `nyan_big` `/proc/cpuinfo` only shows 1 CPU...).

diff --git a/test/tests/x0-alltargets b/test/tests/x0-alltargets
--- a/test/tests/x0-alltargets
+++ b/test/tests/x0-alltargets
@@ -3,39 +3,42 @@
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
 
+if [ -z "$release" ]; then
+    echo "all"
+    exit 0
+fi
+
 # All supported releases should be able to install all targets, unless
 # explicitly blacklisted (exit status 99)
-for release in $SUPPORTED_RELEASES; do
-    for target in "$SCRIPTDIR/targets/"*; do
-        target="${target#$SCRIPTDIR/targets/}"
+for target in "$SCRIPTDIR/targets/"*; do
+    target="${target#$SCRIPTDIR/targets/}"
 
-        # Ignore *common targets
-        if [ "${target%common}" != "$target" ]; then
-            continue
-        fi
+    # Ignore *common targets
+    if [ "${target%common}" != "$target" ]; then
+        continue
+    fi
 
-        # Some other targets do not require testing in this context
-        for blacklist in audio core x11 xephyr xorg; do
-            if [ "$target" = "$blacklist" ]; then
-                break
-            fi
-        done
+    # Some other targets do not require testing in this context
+    for blacklist in audio core x11 xephyr xorg; do
         if [ "$target" = "$blacklist" ]; then
-            continue
+            break
         fi
-
-        # Start with a x11 snapshot, as most targets depend on it
-        snapshot "$release" x11
-        ret=0
-        crouton -u -n "$release" -t "$target" || ret=$?
-        if [ "$ret" -ne 0 ]; then
-            if [ "$ret" -eq 99 ]; then
-                log "Target $target failed on $release, as expected (unsupported combination)."
-            else
-                log "Target $target failed on $release."
-                exit "$ret"
-            fi
-        fi
-        host delete-chroot -y "$release"
     done
+    if [ "$target" = "$blacklist" ]; then
+        continue
+    fi
+
+    # Start with a x11 snapshot, as most targets depend on it
+    snapshot "$release" x11
+    ret=0
+    crouton -u -n "$release" -t "$target" || ret=$?
+    if [ "$ret" -ne 0 ]; then
+        if [ "$ret" -eq 99 ]; then
+            log "Target $target failed on $release, as expected (unsupported combination)."
+        else
+            log "Target $target failed on $release."
+            exit "$ret"
+        fi
+    fi
+    host delete-chroot -y "$release"
 done
