audio: Detect ADHD commit id from manifests if no branch available.
Some recents dev-channel releases have been missing a stabilize
branch in ADHD git (e.g. 5619, see #711).
Also useful for canary/custom-built images.

It is still important to look for a release or stabilize branch,
as the branch may include additional patches (stable/beta).

diff --git a/targets/audio b/targets/audio
--- a/targets/audio
+++ b/targets/audio
@@ -26,12 +26,14 @@ if [ -z "$ADHD_HEAD" ]; then
     # Chrome OS version (e.g. 4100.86.0)
     CROS_VER="`sed -n 's/^CHROMEOS_RELEASE_VERSION=//p' /var/host/lsb-release`"
 
+    # Set CROS_VER_1 to the major version number (e.g. 4100), used later on to
+    # selectively apply patches.
+    CROS_VER_1="${CROS_VER%%.*}"
+
     echo "Detecting CRAS branch (Chromium OS build $CROS_VER)..." 1>&2
 
     ADHD_HEAD="`awk '
         BEGIN {
-            # Default to master if nothing else is found
-            print 0, "master"
             len = split("'"$CROS_VER"'", crosvers, ".")
             # Prepare a regex with each additional version component optional
             for (i = len; i >= 2; i--)
@@ -48,13 +50,38 @@ if [ -z "$ADHD_HEAD" ]; then
         }
     ' "$CRASBUILDTMP/adhd.refs" | sort -V | tail -n 1 | cut -d' ' -f2`"
 
-    # Set CROS_VER_1 to the major version number (e.g. 4100), used later on to
-    # selectively apply patches.
-    CROS_VER_1="${CROS_VER%%.*}"
+    # If no branch can be found, fall back on manifests. This should only be
+    # needed on dev or canary channel, and this cannot be used on stable/beta,
+    # as additional patches may be added to the git branch.
+    if [ -z "$ADHD_HEAD" ]; then
+        echo "No CRAS branch found, falling back on manifests..." 1>&2
 
-    # No patch needs to be applied on master (typical with Chromium OS images)
-    if [ "$ADHD_HEAD" = "master" ]; then
-        CROS_VER_1=999999
+        MANIFEST_GIT="https://chromium.googlesource.com/chromiumos/manifest-versions/+/master/chrome-LKGM-candidates"
+
+        # Get the list of releases (e.g. 35). Only last 2 should be required.
+        majorlist="`wget -O- "$MANIFEST_GIT/buildspecs" \
+            | tr '>' '\n' | sed -n 's|^\([0-9]*\)/<.*|\1|p' \
+            | sort -n -r | head -n 2`"
+
+        for major in $majorlist; do
+            # Get the latest manifest for the current build
+            manifest="`wget -O- "$MANIFEST_GIT/buildspecs/$major" \
+                 | sed -n 's/.*\('"$CROS_VER_1"'.0.0-rc[0-9]*.xml\).*/\1/p'`"
+
+            if [ -n "$manifest" ]; then
+                # Fetch git commit id
+                ADHD_HEAD="`wget -O- \
+                    "$MANIFEST_GIT/buildspecs/$major/$manifest?format=TEXT" \
+                        | base64 -d \
+| sed -n 's|.*path="src/third_party/adhd".* revision="\([0-9a-f]*\)".*|\1|p'`"
+                break
+            fi
+        done
+    fi
+
+    if [ -z "$ADHD_HEAD" ]; then
+        echo "Cannot figure out CRAS branch or commit ID." 1>&2
+        exit 1
     fi
 fi
 
