audio: If master is picked, audio might not work

diff --git a/targets/audio b/targets/audio
--- a/targets/audio
+++ b/targets/audio
@@ -105,7 +105,7 @@ archive="$CRASBUILDTMP/adhd.tar.gz"
 urlbase="https://chromium.googlesource.com/chromiumos/third_party/adhd/+archive"
 if ! wget --content-on-error -O "$archive" "$urlbase/$ADHD_HEAD.tar.gz"; then
     if grep -q "Error 404" "$archive" 2>/dev/null; then
-        echo "Branch not found, falling back on master..." 1>&2
+        echo "Branch not found, falling back on master (audio might not work)..." 1>&2
         ADHD_HEAD="master"
         wget -O "$archive" "$urlbase/$ADHD_HEAD.tar.gz"
     else
