Add target check, and prevent unity+xephyr+!precise, which doesn't work.
Closes #78, although this is obviously not ideal.
This can be reinvestigated once xephyr gets egl support.

diff --git a/targets/unity b/targets/unity
--- a/targets/unity
+++ b/targets/unity
@@ -2,6 +2,11 @@
 # Copyright (c) 2013 The Chromium OS Authors. All rights reserved.
 # Use of this source code is governed by a BSD-style license that can be
 # found in the LICENSE file.
+if [ ! "$TARGETS" = 'help' -a ! "${ARCH#arm}" = "$ARCH" \
+     -a ! "$RELEASE" = 'precise' ]; then
+    echo "unity target does not work in xephyr in $RELEASE due to missing egl support." 1>&2
+    exit 1
+fi
 REQUIRES='chromium gtk-extra x11 core'
 DESCRIPTION='Installs the Unity desktop environment. (Approx. 700MB)'
 HOSTBIN='startunity'
