Fix Xephyr version detection.

diff --git a/targets/xephyr b/targets/xephyr
--- a/targets/xephyr
+++ b/targets/xephyr
@@ -16,9 +16,13 @@ if [ "$RELEASE" = 'quantal' ]; then
     apt-get -y install wget
     url="$MIRROR/pool/universe/x/xorg-server/"
     xvers="`wget -O- "$url" \
-        | sed -n 's/.*\(xserver-xephyr_1\.11\.4-0ubuntu[0-9][0-9]\.[0-9]*_$ARCH\.deb\).*/\1/p' \
+        | sed -n 's/.*\(xserver-xephyr_1\.11\.4-0ubuntu[0-9][0-9]\.[0-9]*_'"$ARCH"'\.deb\).*/\1/p' \
         | sort -V | tail -n1`"
-    url="$url/${xvers:-xserver-xephyr_1.11.4-0ubuntu10.12_$ARCH.deb}"
+    if [ -z "$xvers" ]; then
+        echo 'Error retreiving latest Xephyr version.' 1>&2
+        exit 1
+    fi
+    url="$url/$xvers"
     deb='/tmp/xephyr.deb'
     rm -f "$deb"
     wget --no-check-certificate "$url" -O "$deb"
