Removed redirects in function echo_color, now the caller is responsible. Added yellow color to a few error 3 calls in functions. Only error with exit 1 is now by default red. On other exit codes the color need to be added in the error call. Changed l(ight) to t(hick), because "1;" sets the lettertype to bold.

diff --git a/installer/functions b/installer/functions
--- a/installer/functions
+++ b/installer/functions
@@ -40,12 +40,12 @@ installscript() {
 # Exits the script with exit code $1, spitting out message $@ to stderr
 error() {
     local ecode="$1"
-    local color="lred"
     shift
-    if [ "$ecode" -ne 1 ]; then
-        color="lyellow"
+    if [ "$ecode" -eq 1 ]; then
+        echo_color "r" "$*" 1>&2
+    else
+        echo "$*" 1>&2
     fi
-    echo_color "$color" "$*"
     exit "$ecode"
 }
 
@@ -131,18 +131,18 @@ alias getopts_nextarg='getopts_ret=1
 # Example:  release -ge quantal -ge wheezy
 release() {
     if [ "$(($# % 2))" -ne 0 ]; then
-        error 3 "invalid parameters to release(): $*"
+        error 3 "$(echo_color "y" "invalid parameters to release(): $*")"
     fi
     # Load up the list of releases; this will be replaced with a literal list
     local releases="`cat "$DISTRODIR/releases" 2>/dev/null`"
     if [ -z "$releases" ]; then
-        error 3 "list of releases for $DISTRO not found"
+        error 3 "$(echo_color "y" "list of releases for $DISTRO not found")"
     fi
     # End-of-word regex for awk
     local eow='([^a-z]|$)'
     local relnum="`echo "$releases" | awk "/^$RELEASE$eow/ {print NR; exit}"`"
     if [ -z "$relnum" ]; then
-        error 3 "$RELEASE not found in $DISTRO"
+        error 3 "$(echo_color "y" "$RELEASE not found in $DISTRO")"
     fi
     while [ "$#" -ge 2 ]; do
         local cmp="`echo "$releases" | awk "/^$2$eow/ {print NR; exit}"`"
@@ -224,24 +224,24 @@ echo_tty() {
     fi
 }
 
-# Outputs colored text to stderr
+# Outputs colored text to stdout
 # usage: echo_color [l][color] [string]
-# Specifying "l" uses the light version of the color.
+# Specifying "t" (thick) uses bold text.
 # Color can be red, green, yellow, blue, magenta, cyan.
 # Color can be specified with just the first letter. 
-# example: echo_color "lr" "light red"
+# example: echo_color "tr" "bold red"
 echo_color() {
     # If not outputting to a tty print no colors.
     if [ ! -t 2 ]; then
         shift
-        echo "$@" 1>&2
+        echo "$@"
         return
     fi
     printf "\033["
     local c="$1"
-    if [ "${c#l}" != "$c" ]; then
+    if [ "${c#t}" != "$c" ]; then
         printf "1;"
-        c="${c#l}"
+        c="${c#t}"
     else
         printf "0;"
     fi
@@ -260,7 +260,7 @@ echo_color() {
         s=''
         shift
     fi
-    echo '-n' "$@" 1>&2
+    echo '-n' "$*"
     printf "\033[0m$s"
 }
 
