Make croutonwheel work with both gawk and mawk.
gawk does not support -W interactive: use fflush() instead (not POSIX, but supported by mawk and gawk).
However mawk does not obey fflush properly, so we still need to use -W interactive (see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593504)...

mawk is faster, so we prefer it if it is available, and fallback on gawk.

Time to parse ~300K croutonxi2events, on a Samsung ARM Chromebook:

Original code, using mawk:
real	0m9.746s
user	0m6.540s
sys	0m1.340s

Modified code, using mawk:
real	0m9.728s
user	0m5.825s
sys	0m1.315s

Modified code, using gawk:
real	0m11.212s
user	0m9.070s
sys	0m1.320s

Modified code performs identically to original one on mawk. gawk incurs a ~50% performance penalty.

diff --git a/installer/functions b/installer/functions
--- a/installer/functions
+++ b/installer/functions
@@ -110,3 +110,22 @@ release() {
 disablehungtask() {
     echo 0 > /proc/sys/kernel/hung_task_panic
 }
+
+# Detect a version of awk that can be asked not to buffer its output.
+# Prefer mawk, fallback on gawk (~50% slower).
+# mawk needs '-W interactive' to flush the output properly (fflush does not
+# work as documented, but apparently this behaviour is intentional, see
+# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=593504).
+# Furthermore, fflush is not POSIX so we cannot use any other awk flavor.
+# In the awk code, all print must be followed by fflush, even if it is not
+# necessary with mawk.
+detectawk() {
+    if which mawk >/dev/null 2>&1; then
+        echo -n "mawk -W interactive"
+    elif which gawk >/dev/null 2>&1; then
+        echo -n "gawk"
+    else
+        echo "Cannot find mawk or gawk." 1>&2
+        return 1
+    fi
+}
